### ISSUE TITLE
Update portrayal of sector arc extension

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#10]
Update PC to support final recommendation from [Light sector arc extension](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/26)

**Comment by mikan66** [comment]
See final decision at https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/26#issuecomment-1182664153

**Comment by DavidGrant-NIWC** [comment]
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/114#issuecomment-1428788449

![image](https://user-images.githubusercontent.com/62906211/218592171-665485b2-c3f6-49f2-94bd-9049f0769693.png)

Change sector extension length from 3mm to 5mm.
