### ISSUE TITLE
Implement S-52 PL 4.0(.3) changes

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#11]
Implement S-52 changes: 4.0(.2) -> 4.0(.3)

|**PresLib Ed. 4.0(.3) clause**|**Clarification**|**Justification**|**Effect on S-101 PC**|
|:---|:---|:---|:---|
|Chart 1 related changes|[...]|[...]|None|
|Part I – Annex C Look-up Table Areas Symbolized Boundaries|Amend Viewing Group for BRIDGE text (OBJNAM) from 21 to 26.|Make the Look-up Table consistent with Part 1 clause 14.4.|Update Bridge.lua|

**Comment by JoeMassey-WRSystems** [comment]
The PL 4.0(.3) lookup tables for plain boundaries and lines still contain the incorrect viewing group 21.  I'm sure this is not the intent.  Do we want to apply the corrections for plain boundaries and lines to the S-101 PC?

**Comment by DavidGrant-NIWC** [comment]
I'll report to ENCWG chair via email:
* DAI still uses 21 for all cases
* Appendix B uses 21
* Appendix C uses 26

Unless someone objects we should update to use 26 as documented in S-52 14.4 and S-98.
