### ISSUE TITLE
Signal Station Traffic (row 25 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#111]
See spec at: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/48#issuecomment-1184007385

Symbol file correction based on spec, 'Symbol Signal Station Traffic' developed by KHOA (first one from the top) : https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/48#issue-1162384212

**Comment by mikan66** [comment]
Posted Day/dusk/night screenshots to PSWG #48.  Waiting on feedback.

**Comment by mikan66** [comment]
See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/e13d70e8961a0204c231e3f021b2165ca7073c4d

**Comment by mikan66** [comment]
rename to SISTAT03.svg vs 2022_SISTAT03.svg

**Comment by mikan66** [comment]
symbol and name change commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/ef63f052e4a805a5e1b131f333508c2439242ee8

**Comment by alvarosanuy** [comment]
Symbol SISTAT_03 must come up as a central symbol for Surfaces. NIWC's screenshot seems to be Ok.

What TDS S-1 cell is that one?
@TomRichardson6 - Is there a document that lists all the Test Cases and the cells you need to open to visualize them?

**Comment by TomRichardson6** [comment]
@alvarosanuy the test cases are numbered based on the DCEG so there is no separate index you should be able to use the DCEG. The spec documents in Github then detail the specific encoding scenarios. 

@mikan66 the screenshot in the document should be ignored those were created using an old PC the idea was to update once the new PC was available but capacity is limited so my suggestion here is to remove these as the documents are updated they are only the specs to assist those editing the Test Datasets anyway.

**Comment by mikan66** [comment]
This issue looks complete with supporting test data.
