### ISSUE TITLE
Display Uncertainties (row 45 main) (now only intended for application to A&I)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#115]
Discussion and specs: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/1

**Comment by mikan66** [comment]
@DavidGrant-NIWC  assigning to you for final action.  This looks like OBE and should be closed.

**Comment by DavidGrant-NIWC** [comment]
This should now be "Uncertainties applied to A&I" - I'll update the title.

This should remain open while https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/88#issuecomment-1833095802 is open, but I suspect this will have to be implemented via guidance in S-98 and OEM hard-coding. S-100 doesn't support buffering spatial objects associated with features. It would be a pretty simple addition to S-100, but we can't add any changes.

For point objects we could output a circle (via augmented geometry), but there is no easy solution that I see for curves or surfaces.

**Comment by DavidGrant-NIWC** [comment]
Related: #314

**Comment by DavidGrant-NIWC** [comment]
Per https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/160 this will not be included in 1.3

**Comment by DavidGrant-NIWC** [comment]
Direction is that portrayal will not be responsible for portraying accuracy information or applying to alerts. This will become an OEM responsibility and direction will be provided in S-98 Annex C.

Closing as OBE
