### ISSUE TITLE
up-to Portrayal-Register's portrayal-catalogue?

### ISSUE THREAD

**Issue by Dirk--** [iho-ohi/S-101_Portrayal-Catalogue#13]
http://registry.iho.int/portrayal/list.do lists 935 symbols, this catalogue 572 (I guess, inlandECDIS is missing).
Is there a complete (downloadable) catalogue somewhere?

http://registry.iho.int/productspec/view.do?idx=78&product_ID=S-101 : 'Portrayal Catalogue 0.9.3' seems to be rather old ...

**Comment by DavidGrant-NIWC** [comment]
>http://registry.iho.int/portrayal/list.do lists 935 symbols, this catalogue 572 (I guess, inlandECDIS is missing).

You can filter by domain to restrict the number of symbols, but even then it is the symbols from all registered products in that domain.
![image](https://user-images.githubusercontent.com/62906211/129632455-b0b3ed0c-2ecb-44d5-9e58-93b1770cf885.png)

> Is there a complete (downloadable) catalogue somewhere? http://registry.iho.int/productspec/view.do?idx=78&product_ID=S-101 : 'Portrayal Catalogue 0.9.3' seems to be rather old ...

The catalog maintained in this repo is currently used by the S-101 working group for evaluation and prototyping in the test beds.
