### ISSUE TITLE
Implement 2 preferred QoBD portrayal options [PSWG #113]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#135]
CREATE TWO PROTOTYPE BRANCHES FOR THIS ISSUE, one for each of 2 preferred Q0BD visualizations:

See full spec at: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/113#issue-1470691591

Amend existing QoBD rule to accommodate the 2 preferred visualization options identified by UNHCCOM in unique PC 1.1.0 versions.

Also see Alvaro email from Thu 12/1/2022 7:59 PM.

**Comment by DavidGrant-NIWC** [comment]
Implementation can mostly be copied from the catzoc-alternate-portrayals branch.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/eab360cf-9cf0-4553-bad8-a34a536fa82e)

**Comment by DavidGrant-NIWC** [comment]
OBE - a single `QoBD` portrayal option has been selected.
