### ISSUE TITLE
Portrayal Impact Analysis - FC/DCEG 1.1.0 vs PC 1.0.2 [PSWG #114]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#136]
Review deltas as indicated at: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/114#issue-1472333472

**Comment by mikan66** [comment]
From Jeff, (converted to docx). 
[S101_Data Classification and Encoding Guide_1.1.0_Final Draft_Redline.docx](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/files/10166029/S101_Data.Classification.and.Encoding.Guide_1.1.0_Final.Draft_Redline.docx)

**Comment by DavidGrant-NIWC** [comment]
Hey Mikan,

Please send to ***@***.***


David Grant

NIWC Atlantic 52400

(757) 541-5794 (w)

(312) 578-5794 (dsn)

(757) 708-4611 (m)


Disclaimer: I am not a contracting officer, authorized buyer, or other person authorized to make  contracts, purchases or business agreements of any kind. Requests for information or quotes do not constitute or imply a contract or other agreement of any kind.

________________________________
From: mikan66 ***@***.***>
Sent: Tuesday, December 6, 2022 7:03 AM
To: iho-ohi/S-101_Portrayal-Catalogue ***@***.***>
Cc: Grant, David M (52400) CIV USN NIWC ATLANTIC VA (USA) ***@***.***>; Assign ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re: [iho-ohi/S-101_Portrayal-Catalogue] Portrayal Impact Analysis - FC/DCEG 1.1.0 vs PC 1.0.2 [PSWG #114] (Issue #136)


From Jeff, (converted to docx).
S101_Data Classification and Encoding Guide_1.1.0_Final Draft_Redline.docx<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2Fiho-ohi%2FS-101_Portrayal-Catalogue%2Ffiles%2F10166029%2FS101_Data.Classification.and.Encoding.Guide_1.1.0_Final.Draft_Redline.docx&data=05%7C01%7Cdavid.m.grant22.civ%40us.navy.mil%7Ce567c819723b405c33e508dad7820f83%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C638059254270455682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fJvGhWdaUkUeu9kAjBBZ20sAmbK1qyGKYEsUF5QM%2FnM%3D&reserved=0>

**Comment by DavidGrant-NIWC** [comment]
Covered by:
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/114#issuecomment-1428788449
