### ISSUE TITLE
Incorrect drawing of some Complex line styles [PSWG #89]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#140]
Spec at: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/89#issuecomment-1379609298

**Comment by DavidGrant-NIWC** [comment]
Update the following line styles using files provided in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/89
* DWLDEF01.xml
* DWRTCL05.xml
* DWRTCL06.xml
* DWRTCL07.xml
* DWRTCL08.xml
