### ISSUE TITLE
symbol SOUNDSC2

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#141]
The symbol SOUNDSC2 for low accurate soundings inferior or equal to the safety depth does not have the correct color.
Proposal : In the definition of the symbol SOUNDSC2  Change the color SNDG1 to SNDG2.

**Comment by mikan66** [comment]
@alvarosanuy should we move this over to PSWG for discussion?  Only agreed upon specific actions/decisions should be here, no proposals.

**Comment by mikan66** [comment]
See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/b3947ccc41198d1e7c0cfe3f8f970cf7d586c8fb
and picture at: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/118#issuecomment-1434875931

**Comment by mikan66** [comment]
Dave found issues with his dataset, investigating...

**Comment by mikan66** [comment]
See revision commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/fab6084bdf40ea8cc41dbde970f9a94a4ce2dc46

**Comment by DavidGrant-NIWC** [comment]
Confirmed portrayal using test dataset with Safety depth set to 3.7:
![ShoreECDIS 2023-08-01T183458Z](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/fab81ec5-eb1e-4aa7-8131-1c9c08fa6cff)
