### ISSUE TITLE
New symbol for Berth features with categoryOfCargo = 7 (Dangerous or Hazardous) - ENCWG7-5.3_2022 [PSWG #112]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#142]
SPEC at: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/112#issuecomment-1381193928

**Comment by mikan66** [comment]
Need test data for this one: categoryOfCargo = 7 .  I can't simulate this.

**Comment by TomRichardson6** [comment]
@mikan66 I have noted an edit for Test Dataset 008 to support testing this, this will require FC 1.1.0 but I hope to get these edits underway very soon.

**Comment by mikan66** [comment]
Implemented and tested logic.  Will need to finish when test data available.

![image](https://user-images.githubusercontent.com/4913543/216778629-5a1455dc-3a86-4bbc-846f-452905a12e23.png)

![image](https://user-images.githubusercontent.com/4913543/216778657-14bfd7ee-82a2-43af-b4ca-474e9b74d07f.png)

**Comment by mikan66** [comment]
Not tested with new FC.  Forced code path testing does not crash but throws error.  Needs real data for testing.
local categoryOfCargo = Feature.categoryOfCargo

See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/4a606ba5a2709dc3b8f28ba71c3f9977eb9d870f

**Comment by mikan66** [comment]
needs case correction:  Feature.categoryOfCargo   => feature.categoryOfCargo

**Comment by mikan66** [comment]
case correction: Feature.categoryOfCargo => feature.categoryOfCargo and added comment at top of file for issue update

Commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/68416bb051b2d5c0232291b8603d963181917fd8

**Comment by mikan66** [comment]
Test with official dataset 101AA00DS0008.000.  Rule evaluation doesn't seem correct.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/9f984c27-cbaf-4e57-aaf6-4e6042727f8f)
