### ISSUE TITLE
symbols: UTF-8-BOM encoding

### ISSUE THREAD

**Issue by Dirk--** [iho-ohi/S-101_Portrayal-Catalogue#15]
looks like 
```
SAFCON50.svg
SAFCON51.svg
SAFCON52.svg
SAFCON53.svg
SAFCON54.svg
SAFCON55.svg
SAFCON56.svg
SAFCON57.svg
SAFCON58.svg
SAFCON59.svg
```
are UTF-8-BOM encoded.
Guess, all symbols should be UTF-8 encoded, instead ?

**Comment by DavidGrant-NIWC** [comment]
BOM is optional for XML: https://www.w3.org/TR/REC-xml/#sec-guessing

![image](https://user-images.githubusercontent.com/62906211/129631910-548987c7-540b-4f0a-be48-a829bb53db38.png)
