### ISSUE TITLE
symbols: viewBox mismatch

### ISSUE THREAD

**Issue by Dirk--** [iho-ohi/S-101_Portrayal-Catalogue#16]
both, Portrayal-Register's and this Portrayal-Catalogue's symbols do need viewBox adjustments:
```
BCNGEN03 viewBox height mismatch
EMDRGRE1 viewBox height mismatch
EMDRGRE2 viewBox height mismatch
EMMARS02 viewBox height/width mismatch
```

**Comment by mikan66** [comment]
@alvarosanuy and @Dirk, what is further guidance on this issue?  We typically are not adjusting individual symbols and leave that to HOs.

**Comment by alvarosanuy** [comment]
Is this the result of converting the S-52 symbology into SVG files? Was this automated by Caris (@TDYCARHugh)??

If there's evidence the SVG viewBox is wrong we can either:

- [ ] Ask NIWC to fix it and supply Alvaro the amended file for its update in the GI Registry
- [ ] Create a new GitHub issue in the PsWG space to discuss the need, etc.

I'd prefer the first option but I understand NIWC may want to socialise this issue first (and get 'approval') before making any changes to the SVG files.

**Comment by TDYCARHugh** [comment]
Looking quickly into BCNGEN03 it appears that the mixed line width values may not have been handled correctly when calculating the viewbox and width/height for some symbols.  I will look into it further. Luckily I still have the artifacts from 6+ years ago.

**Comment by DavidGrant-NIWC** [comment]
See also related issue #17 (the viewbox for all SAFCON5X are incorrect). I believe the pivot point for the SAFCON5X symbols was incorrect in S-52; not sure if that issue has been fixed in the latest S-52 PresLib.

Any updated symbols must also be updated in the portrayal registry.

**Comment by mikan66** [comment]
> Looking quickly into BCNGEN03 it appears that the mixed line width values may not have been handled correctly when calculating the viewbox and width/height for some symbols. I will look into it further. Luckily I still have the artifacts from 6+ years ago.

@TDYCARHugh Looks like you have last action here. I don't think we have the tools to adjust the viewBox.  The KHOA symbol builder is rather basic and I don' that will get the job done.  I'm going to re-assign this to you.

**Comment by TDYCARHugh** [comment]
[AdjustedSymbols.zip](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/files/10733678/AdjustedSymbols.zip)

I manually adjusted the 4 symbols listed by Dirk. Attached.

**Comment by DavidGrant-NIWC** [comment]
@TDYCARHugh it looks like EMDRGRE2 wasn't updated - I changed it based on your other changes. I also updated the symbols to reference daySvgStyle.css instead of SVGStyle.css.
