### ISSUE TITLE
Update feature catalog to 1.1.0

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#163]
Update the feature catalog when the official catalog is available.

**Comment by alvarosanuy** [comment]
**Please check with @JWootton** as he mentioned to me yesterday that FC 1.1.0 won't be uploaded to the GI Registry until PC 1.1.0 is ready ........ He mentioned that the latest FC 1.1.0 version is available in the DCEG Github space. Input from FC review has been included except for Associations that would be moved to a later version. Minor comments, etc wouldn't be included in FC 1.1.0 (as he wants to avoid further changes to a version that has been 'technically' already approved by S100WG). He is including these changes into a draft FC 1.2.0.

**Comment by DavidGrant-NIWC** [comment]
Will update to: [S-101 FC v1.1.0](https://github.com/iho-ohi/S-101-Documentation-and-FC/tree/main/S-101FC/version%201.1.0)

Note that this is only provided here for convenience / testing / developmental purposes. The FC is not part of the PC distribution.

**Comment by DavidGrant-NIWC** [comment]
Updated via https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/44f421e10d3017663a2222d7b2375a563510e83e
