### ISSUE TITLE
SAFCON54 not in sync

### ISSUE THREAD

**Issue by Dirk--** [iho-ohi/S-101_Portrayal-Catalogue#17]
- Portrayal-Register's shows correct symbol
- Portrayal-Catalogue's shows wrong symbol

**Comment by DavidGrant-NIWC** [comment]
Portrayal Register update proposal matches PC (original SAFCON5X symbols have pivot point error inherited from S-52):
![image](https://user-images.githubusercontent.com/62906211/129629432-891ef7a7-d916-44b6-ae1b-ed664a5de5cf.png)

All SAFCON5X symbols have viewBox issue - note clipping visible in SAFCON55.svg:
![image](https://user-images.githubusercontent.com/62906211/129629712-bfd7b24a-f1d4-4fef-ad9a-805ca7cf06f4.png)

SAFCON54 has incorrect stroke-width of 0.0064 (should be 0.96 for sDEPDW and 0.32 for sSNDG2) in addition to clipping issue:
![image](https://user-images.githubusercontent.com/62906211/129630210-42ad4400-3a5f-4219-8234-52592a3d00d1.png)

**Comment by DavidGrant-NIWC** [comment]
- [ ] Update SAFCON5X from SAFCON6X
- [ ] Move pivot points
- [ ] Ensure symbols aren't clipped by viewBox
- [ ] Verify pivot points are correct
- [ ] Notify portrayal register manager of updated symbols

**Comment by mikan66** [comment]
This has been hanging out there for a while and I'm not sure 5X or 6X are entirely correct.  Experimenting with 54 from 64 (bullet 1 above from Dave) and some other 6X "as-is", these all look suspicious with being clipped as compared to S-52.  Most other S-101 symbols don't bleed over the dark-blue outline.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/28f90796-b60e-4218-892b-631a7ba56c99)

**Comment by mikan66** [comment]
Before: 
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/705b6cd7-fe3a-4cb8-ad75-fda69bc224c1)

After: 
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/285fc2fd-a93f-4102-9936-b809e9522550)

There's more to it than just viewbox because there is a relationship with "width" and "height".  Corrected with Inkscape.

**Comment by DavidGrant-NIWC** [comment]
Check the placement against the S-52 symbol catalog (make sure the SVG viewbox 0, 0 coordinate corresponds to the S-52 pivot point position):

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/16b7c35e-c42c-42c1-a2d2-e6b1258afbf8)

**Comment by alvarosanuy** [comment]
If possible, recommend prioritizing for PC 1.2.0

**Comment by mikan66** [comment]
@alvarosanuy, Here are the updated SAFCON5X view-box and pivot-point offsets to more closely match S-52 symbols.  This better than before but probably not perfect.  I would register these as "version 1.0".
[SAFCON5X_Updated.zip](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/files/14363860/SAFCON5X_Updated.zip)

**Comment by mikan66** [comment]
See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/7070207e7de4ecf2d294a45c26002701ebeb874e
