### ISSUE TITLE
Ensure correct handling of `featureName` with `nameUsage` (was `displayName`)

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#175]
[PSWG Issue comment](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/104#issuecomment-1452780125)

A `featureName` which has every `displayName` attribute set to `false` should not output any drawing instructions related to drawing the name. GetFeatureName() will return nil, which could impact the output.
* Investigation reveals that calling S100Scripting.EncodeString(str) will convert a nil value to an empty string (''), so any output text instruction will be `TextInstruction:`. This is valid, so addressing this issue is considered an enhancement.

**Comment by DavidGrant-NIWC** [comment]
`displayName` was remodeled as `nameUsage` - the issue still applies.

**Comment by DavidGrant-NIWC** [comment]
Follow the link to download a dataset containing a feature with multiple names: https://github.com/iho-ohi/S-164-Sub-Group/issues/69#issuecomment-1934566075

You could ask JP to add `nameUsage`=`No chart display` (3)

**Comment by mikan66** [comment]
We already tested:
 single name, nameUsage=1 
 single name, nameUsage=3 (pick report only) 
 two names, two languages, one default (nameUsage=1), one alternate (nameUsage=2). 

Maybe for this case from DCEG v1.2.0, page 21.

 If it is required to restrict the display of all instances of feature name encoded for a feature
instance only to the ECDIS Pick Report, name usage must not be populated for any instance

**Comment by DavidGrant-NIWC** [comment]
Fixed via #334
