### ISSUE TITLE
Remove CSS inline styling from symbols [PSWG #124]

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#177]
CSS inline styling is not permitted in SVG Tiny 1.2 and must be removed.

[PSWG corresponding issue](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/124)
[CSS inline styling not permitted](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/103#issuecomment-1448536951)

**Comment by DavidGrant-NIWC** [comment]
@DavidGrant-NIWC wrote:
> The inline styling can be removed - the 5.0 schema doesn't require the class attribute to be present, it just (incorrectly) allows it to be present.

@HolgerBothien replied:
>It is not about the class attribute,.
The ed 5 schema doesn't allow the fill, stroke, stroke-width, etc attributes.
So making style="stroke-width: 0.32;" to stroke-width="0.32" would make the file non-schema conform.

You are of course correct. In my opinion this is a bug in the S-100 5.0 which should be corrected. We'll defer implementation of this issue until the schema is corrected (maybe in 5.2?) or updated in S-100 edition 6.0.

**Comment by HolgerBothien** [comment]
Yes, this should be corrected. With my proposed new SVG profile and the associated schema it would be corrected.
The symbols can be transformed by an XSLT script.
It wasn't discussed at TSM9 probably none of the key persons was there.
Seems to be we have to wait until November. :-(

**Comment by alvarosanuy** [comment]
Have you bee able to try UNH (Christos K.) converter? Would it help with a global change to all your PC files? Would this converter also help with metadata changes (assuming S100 5.2.0 will be endorsed by MS in mid March).

**Comment by mikan66** [comment]
See S-101PT12 action 07.2:  UNH to provide the converted S101 symbol set to NIWC; and the Tiny-to-IHO SVG Translator and 
CSS Inline Style Removal tools to the IHO Sec. NIWC to include the converted symbols in the next version of the S-101 Portrayal 
Catalogue.
