### ISSUE TITLE
Lost presentation of Anchorage area

### ISSUE THREAD

**Issue by LeoKuzmin** [iho-ohi/S-101_Portrayal-Catalogue#184]
Presentation of the Anchorage Area has been commented out in the AnchorageArea.lua script. Now it is replaced by presentation of ArchipelagicSeaLane function.
Could you provide me a reason of so cardinal changes of Anchorage Area features depiction?

**Comment by mikan66** [comment]
This could be an oversight to remove the test case without data.  I will investigate that merge and open a new issue once I figure out the situation.

**Comment by mikan66** [comment]
Good catch @LeoKuzmin. Confirmed inadvertent check-in of No Geometry test use of AnchorageArea.lua for other no geometry test cases.  Rule state restored.  Should be fixed with commit: [d908f50](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/d908f50a64eaaea40d17e6da8551f8c02ab0a7a6)
