### ISSUE TITLE
Inconsistent colours of dash line and embedded symbol for NAVARE52 linestyle

### ISSUE THREAD

**Issue by LeoKuzmin** [iho-ohi/S-101_Portrayal-Catalogue#186]
The NAVARE52 line style consists of a dash line with colour CHGRF and an embedded symbol EMAREGR1 which has CHGRD colour.
I suppose, it would be logical to have an embedded symbol with the same colour as the dash line.
Or another way, to remove the NAVARE52 line style and replace it with NAVARE51 style since it is just used in one place: in the AnchorageArea.lua script for borders of Small Craft Mooring Area.

**Comment by DavidGrant-NIWC** [comment]
Agrees with intent of https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/28, originally implemented via #124.

- [ ] Create new symbol EMAREGR2.svg (same as EMAREGR1.svg but use color CHGRF)
- [ ] Update NAVARE52.xml
- [ ] Update portrayal_catalogue.xml
- [ ] Notify PSWG
