### ISSUE TITLE
Sounding numbers using font instead of SVG?

### ISSUE THREAD

**Issue by halset** [iho-ohi/S-101_Portrayal-Catalogue#19]
Would it be possible to use S-100 NumericAnnotation instead of PointInstruction for soundings and other SNDFRM04 numbers for increased readability and performance? NumericAnnotation in S-100 mention subscript for decimals, so that should be covered.

**Comment by DavidGrant-NIWC** [comment]
Using fonts for soundings enhances readability. However, exact placement and scaling using fonts may be difficult to guarantee in all OEM ECDIS systems without investing in additional testing / test datasets.

If desired, this should be proposed to the S-101 portrayal sub-working group:
[S-100 Portrayal sub-WG Issues](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

**Comment by halset** [comment]
@DavidGrant-NIWC , thank you.
