### ISSUE TITLE
Issues with Landmark categoryOfLandmark = 22 (Triangulation Mark), 24 (Observation Wheel), and 25 (Torii)

### ISSUE THREAD

**Issue by LeoKuzmin** [iho-ohi/S-101_Portrayal-Catalogue#191]
According to the current Landmark.lua script a landmark feature of geometry type point with category of Landmark equal to 25(torii) will be displayed incorrectly.
The action will never fall into the last branch of the algorithm to display Torri Landmark:
```
elseif feature.PrimitiveType == PrimitiveType.Point then
		-- Issues: PSWG #60, PC #104 (NOT AUTO GENERATED)
		if contains(25, feature.categoryOfLandmark)
```
We always fall into the second branch of algorithm:
`	elseif feature.PrimitiveType == PrimitiveType.Point then
`

In this case the POSGEN01 symbol will be displayed for the Torri Landmark.

If we want to display new symbols TORII01, TORII11 and POSGEN05 for Triangulation Mark for case where contextParameters.SimplifiedSymbols equal to "false", all conditions from the lates branch must be moved to the second branch.
If we want to display them independently on contextParameters.SimplifiedSymbols, they must be duplicated in the first branch too.

**Comment by DavidGrant-NIWC** [comment]
See #104 

* Move code to appropriate branch
* Add support for simplified symbols
* Fix viewing group assignment for non-conspicuous Torii

**Comment by mikan66** [comment]
Test data still needed.

**Comment by alvarosanuy** [comment]
@tomrichardson - Can you please arrange a TDS case for the 3 features in this issue???
