### ISSUE TITLE
Incorrect portrayal of Signal Station Traffic

### ISSUE THREAD

**Issue by LeoKuzmin** [iho-ohi/S-101_Portrayal-Catalogue#195]
Currently Signal Station Traffic is displayed as a Signal Station Warning.
According to the SignalStationTraffic.lua script the symbol SISTAT03 must be presented. However, the SISTAT03.svg file depicts the SSW symbol:
![image](https://user-images.githubusercontent.com/106175259/227156580-e0364b6a-f33c-4fb7-8fb5-02a6084f9b9c.png)
Actually, the SST symbol is drawn by the 2021_SISTAT02_01.svg file:
![image](https://user-images.githubusercontent.com/106175259/227157469-77bfd20e-0a47-4c4f-a48d-a5fc20ec3689.png)

**Comment by DavidGrant-NIWC** [comment]
See also #111 and #112

2021_SISTAT02_01.svg should probably be removed - investigate PSWG discussion and related issues.

**Comment by LeoKuzmin** [comment]
I suppose 2021_SISTAT02_01.svg should be renamed to SISTAT03

**Comment by DavidGrant-NIWC** [comment]
SISTAT02.svg is not cataloged in portrayal_catalogue.xml

**Comment by mikan66** [comment]
I'm guessing "signal station" was split out into "traffic" and "warning".  I will remove 2021_SISTAT02_01 references and the file.   From PSWG #48, 2022_SISTAT03.svg was decided to be SISTAT03.svg.

**Comment by mikan66** [comment]
See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/e28a4973a0d8337018d8c5d5e8171975997cb63e
