### ISSUE TITLE
Viewing Groups 26010 and 26020 have identical names

### ISSUE THREAD

**Issue by LeoKuzmin** [iho-ohi/S-101_Portrayal-Catalogue#196]
Viewing groups with id equal to 26010 and 26020 are described identical in portrayal_catalogue.xml where:
```
         <description>
            <name>Restricted area (RESARE)</name>
            <description>Standard: N - Special areas</description>
            <language>eng</language>
         </description>
```
I suppose it will confuse customers.
I suggest renaming of the viewing groups:
 -  26010 as "Restricted area, Navigational (RESARE)"
 -  26020 as "Restricted area, Regulatory (RESARE)"

**Comment by DavidGrant-NIWC** [comment]
Genesis: [PSWG issue 31](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/31)

Related: [PSWG issue 131](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/131), [PSWG issue 132](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/132)

**Comment by DavidGrant-NIWC** [comment]
![image](https://user-images.githubusercontent.com/62906211/227256597-74a397d6-767c-41d8-b4f8-6154ac1bd936.png)
