### ISSUE TITLE
Undefined parameter TwoShades for ShallowContour and DeepContour

### ISSUE THREAD

**Issue by LeoKuzmin** [iho-ohi/S-101_Portrayal-Catalogue#197]
There are conditions for assigning parameters  ShallowContour and DeepContour that are determined by the values of the parameter TwoShades:
```
      <parameter id="ShallowContour" enable="//TwoShades[1]='false' or //TwoShades[1]='0'">
...
      <parameter id="DeepContour" enable="//TwoShades[1]='false' or //TwoShades[1]='0'">
```
However, the TwoShades parameter is not defined in PC. There is the parameter "FourShades" which is opposite for TwoShades.

Besides of that there is a text on Korean language for ShallowContour and DeepContour parameters. I suppose global PC should not include specific things.

**Comment by DavidGrant-NIWC** [comment]
Oversight when context parameter names were changed by #155.

See also [PSWG issue 119 comment](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/119#issuecomment-1414397813)

> Besides of that there is a text on Korean language for ShallowContour and DeepContour parameters. I suppose global PC should not include specific things.

See #199

**Comment by DavidGrant-NIWC** [comment]
![image](https://user-images.githubusercontent.com/62906211/227261598-6a7b19c5-3905-4461-8149-b16c45ad1fa8.png)
![image](https://user-images.githubusercontent.com/62906211/227261703-ab866516-e6e9-49f7-a138-0bb8c5ca2afc.png)
