### ISSUE TITLE
Viewing Group 27220 missing for "Range System"

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#198]
Viewing Group 27220 missing for No Geometry feature "Range System" is missing from PC.  See spec at https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/85#issuecomment-1429040850.  No alternatives were proposed.

**Comment by DavidGrant-NIWC** [comment]
* Also needs a viewing group layer assignment in the "Standard Display" section (2 - 10)
  * Check with @alvarosanuy
  * If added to VGL 3
      * need to decide if it should also be in VGL 3.1, or
      * should a new sub-element should be added (3.3 - would need a name and description)

![image](https://user-images.githubusercontent.com/62906211/227266733-c5fc8cbc-2a45-44f6-894a-29dc8c670c67.png)
![image](https://user-images.githubusercontent.com/62906211/227266780-6c986781-af4c-49d6-a214-3fb8d0e0cc71.png)

**Comment by mikan66** [comment]
See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/e28a4973a0d8337018d8c5d5e8171975997cb63e
