### ISSUE TITLE
Viewing Group 27240 is not included in any Viewing Group Layer

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#200]
Viewing groups should be included in at least one viewing group layer. In this case, probably in vgl 3.

![image](https://user-images.githubusercontent.com/62906211/227334813-70c3d333-10de-4d91-868f-5a1e489e60f2.png)

* Need to determine if this should also be added to one of the existing sub-groups (3a)
  * If added, does the name need to be changed?
* or should a new sub-group be created?

[PSWG issue 37](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/37)
[PSWG issue 70](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/70)

**Comment by mikan66** [comment]
Added to 3, removed duplicate entries for <viewingGroup>21020</viewingGroup> at the end of group 3.  
See commit: [9709368](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/9709368123e2e6c05f8a81fc72bed0d44b8670ad)
