### ISSUE TITLE
Symbol validation errors due to missing namespace prefix

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#202]
`<S100SVG xmlns:iho="http://www.iho.int/SVGMetadata">`

should be

`<iho:S100SVG xmlns:iho="http://www.iho.int/SVGMetadata">`

### Applies to
- [x] AISPHY05.svg
- [x] BOYMOR51.svg
- [x] BRTHDNG1.svg
- [x] DSCWTR01.svg
- [x] DSCWTR02.svg
- [x] DSCWTR03.svg
- [x] FERWHL03.svg
- [x] FERWHL04.svg
- [x] FOULGD02.svg
- [x] FOULGD51.svg
- [x] MARSHE01.svg
- [x] MOIRE01.svg
- [x] PILBARE51.svg
- [x] RENERG51.svg
- [x] SISTAT03.svg
- [x] SISTAW03.svg
- [x] SOUNDSC3.svg
- [x] TNKFRM.svg
- [x] WNDFRM52.svg

**Comment by MikusRL** [comment]
My apologies for this mistake in these new symbols. But in my favor, as I was the KHOA Symbol Builder tool user, this is one of many every time overwritten .svg lines in this tool once you open the file for editing. I reported on that to KHOA and IHO (Yong) a couple of times, but the overwriting with their defaults of many of lines is still not fixed in their tool as far as I know. 

Do you want me to update all of these symbols with the fix you are looking for, or will you do this and possibly other fixes in those as part of your overall updates? Thanks.

**Comment by MikusRL** [comment]
@DavidGrant-NIWC Standard output from Symbol builder if one magenta rectangle is created:
![image](https://user-images.githubusercontent.com/72803214/227453826-e15f1909-9b05-4643-86bc-c6b659866260.png)

Perhaps after all this work done by you, @HolgerBothien @mikan66 and Raphael, it would be good for another round of feedback to this tool, what should be as a default lines in the S-100 v5.0.0 compatible .svg file. Just to make more use of it. Or to make a suggestion to discontinue and withdraw it from the official toolkit, if it is not updatable, and suggest other official tools for S-100 symbol creation and maintenance. Perhaps there is a more flexible and adaptable open source tools already to be shaped and used for our purpose. I am just a bit frustrated, that this tool has not been really adaptive, uncomparrable to NIWICs testbead, and that it generates more work for you guys to follow up and fix, making my contributions less helpful and efficient to you and this process.

**Comment by HolgerBothien** [comment]
To be precise the
`<S100SVG xmlns:iho="http://www.iho.int/SVGMetadata">`

should be
`<iho:S100SVG xmlns:iho="http://www.iho.int/SVGMetadata/5.0">`

that is the namespace URI that is used in the S-100 Ed5.0 schema.

The inline styling with the style attribute is not conforming to SVG tiny but converting them now would make the symbols not conforming to the S-100 SVG schema of ed 5.0. So we should keep them for the moment.

**Comment by DavidGrant-NIWC** [comment]
* I'll update the symbols (you can tell because I assigned the issue to myself)
  * @MikusRL, until the symbol builder is updated, we can just run a script to make the necessary changes. I do agree that the tool should be updated, hopefully with the option to output S-100 6.0 compliant symbols.
* This issue only addresses the missing namespace prefix, so that is all that will be changed in the commit tied to this issue
  * I agree with @HolgerBothien that the namespace is also wrong, but I assumed that would be fixed via [PSWG issue 124](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/124#issuecomment-1477404194). I'll add some issues here to track each required change independently.

**Comment by DavidGrant-NIWC** [comment]
Discussion continued in #177

**Comment by DavidGrant-NIWC** [comment]
Forgot to fix the end tags...
