### ISSUE TITLE
Review and update metadata for all PC elements

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#203]
Update metadata per https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/92#issuecomment-1419718682 (also see other comments in this issue)

**Comment by alvarosanuy** [comment]
Can I get an update on this Task please?

**Comment by DavidGrant-NIWC** [comment]
The metadata was updated to conform to the 5.2 schemas, but aside from that I'm not sure exactly how to move this forward.

* @rmalyankar took issue with modifying the metadata in the AreaFills and LineStyles,
  * Example: ![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/0aeb54b1-9b48-4eb7-b830-2ef7dae3e98e)
  * ![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/b841daa2-4a1d-4589-bfb9-b9af128bfbe9)
  * No alternative method for supplying metadata has been provided.
  * Should the processing instructions be removed?
* The symbols contain metadata such as:
  * ![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/5ec34ea6-fd55-4074-933c-68296cd438eb)
  * The meanings of these attributes are defined in S-100: ![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/414289e3-31a4-4963-93f6-bc17a11aa622)
  * Should publisher be changed to "IHO"? [I think yes]
  * Should the version be changed to "1.0"? [I think yes, given that none of these symbols are used in an operational version yet]
  * Should the creationDate be updated? [I think no]
  * Any other changes?
* All the symbols need to be updated in the registry regardless of these changes, but if we are going to change them then they will need to be registered after the changes are made.

**Comment by DavidGrant-NIWC** [comment]
Will be handled at S-100WG level
