### ISSUE TITLE
AnchorageArea incorrect when categoryOfAnchorage has multiple values

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#206]
`categoryOfAnchorage` can have multiple values - need to use contains() and match S-52 processing order.

**Comment by mikan66** [comment]
Checked with fake multiple values.  See commit: [bbd906e](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/bbd906efce0d0d3c13ffec8687d4a27567580acb)
