### ISSUE TITLE
Conveyor.lua has duplicate conditions

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#209]
Reported by @TDYCARHugh
> Conveyor.lua: Several duplicate conditions such as feature.categoryOfConveyor == 1 and feature.radarConspicuous

This is the result of automated conversion of the S-52 rules. In S-52 CONRAD has three possible values, whereas in S-101 radarConspicuous is a boolean. This results in duplication of the radarConspicuous rules (CONRAD = 1 or CONRAD = 3).

Remove duplicate cases.

**Comment by mikan66** [comment]
Removed duplicates, lightly tested with below cell.  See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/1ac0e0bae7d03c565296c33b78c31f7b43f090a3.

![image](https://user-images.githubusercontent.com/4913543/228374225-24a2784f-65c7-4a2f-8056-b90752485ac9.png)
