### ISSUE TITLE
CurrentNonGravitational throws error on curve and surface

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#211]
https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/62

The FC allows curve and surface portrayal. Portray curve and surface using testPCB until final action is determined.

**Comment by mikan66** [comment]
Which is correct?  DCEG 1.1.0 only shows point primitive. 
![image](https://user-images.githubusercontent.com/4913543/228327119-4f58034c-4017-4cff-87aa-9b9260696396.png)

@JeffWootton  @alvarosanuy

**Comment by JeffWootton** [comment]
The DCEG is correct - point is the only allowable geometric primitive for CurrentNonGravitational in S-101.  It was decided that if it was required to encode area current features this would be done by creating a S-111 (Surface Currents) product.

@mikan66 @DavidGrant-NIWC

**Comment by mikan66** [comment]
Present PC implementation appears correct.  A new issued may be needed for the FC to remove other primitives in accordance with DCEG.

**Comment by DavidGrant-NIWC** [comment]
Issue to correct the FC: https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/62
