### ISSUE TITLE
Case inconsistency between filename and catalog entry for SEAGRASS.svg 

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#213]
@HannuPeiponen reports
> portrayal_catalogue.xml contains reference to a symbol called “Seagrass.svg”, but in the symbols folder the filename is “SEAGRASS.SVG” => fix the filename to be same and consistent with naming conventions for other SVG-symbols.

**Comment by mikan66** [comment]
Corrected with commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/8105825f5bee4fc80ea9fc035066cf9606845159

**Comment by mikan66** [comment]
Test data: 101AA00DS0012
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/54db6028-1d1f-4265-9708-e450b45dacac)

See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/c0e8259a18f5505c5454a9a946d17d1d1e24544d
