### ISSUE TITLE
Update version number prior to release

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#215]
Update version from 1.1.1b to 1.1.1

**Comment by mikan66** [comment]
Final change for 1.1.1.  As directed, next version(s) are 1.1.2, 1.1.3, etc until next published drop as 1.2.0.  See this commit:  https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/b0131f9bdf95a01d84ebd913c2955c16e79d1c2f
