### ISSUE TITLE
Symbol SISTAT02.svg has no catalog entry

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#221]
SISTAT02.svg has no entry in portrayal_catalogue.xml

**Comment by mikan66** [comment]
symbol removed, no references to it.  Commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/48b7a1270fbca4b004d2f5669f9a18f420eb648d
