### ISSUE TITLE
Update version prior to release

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#225]
Remove "-DRAFT" from the catalog version attribute and ensure the version number targets the desired release.

**Comment by mikan66** [comment]
Updated to 1.1.2 final. See commit [516acea](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/516acea9c947271c50a2e726042d77f5333d85a9)
