### ISSUE TITLE
Radar station with categoryOfRadarStation = 2 is not showing communication channels

### ISSUE THREAD

**Issue by TDYCARHugh** [iho-ohi/S-101_Portrayal-Catalogue#231]
The lua rule is trying to extract the channels from contactDetails.communicationChannel which is not available from RadarStation   in S-101 1.1. The communicationChannel attribute is directly accessible on the RadarStation feature.

**Comment by DavidGrant-NIWC** [comment]
Agree with @TDYCARHugh. Although `RadarStation` permits binding via `AdditionalInformation`, it only allows the information type on the other end of the binding to be `NauticalInformation`; binding to `ContactDetails` is not supported.

**Comment by DavidGrant-NIWC** [comment]
Related: #92 

I can't find the origin for the change specified in #92 and the change to the modeling was never made.
