### ISSUE TITLE
Difference in display result between S-52 symbols and S-101 due to conversion of dots

### ISSUE THREAD

**Issue by TDYCARHugh** [iho-ohi/S-101_Portrayal-Catalogue#232]
In the original S-52 to S-100 conversion of the symbols sequences with a Pen up and Pen down (without a new position) were converted into a circle.  The circle radius was 0.16 and the linestyle was 0.32.  This resulted in a dot which is larger than the dot which was created by a simple pen down.  The SVG dot using a circle resulted in a dot of 0.64 diameter instead of the 0.32 dot is S-52.

The following symbols were affected:

DANGER01.svg

DANGER02.svg

DANGER03.svg

DRGARE01P.svg

FSHHAV01.svg

OBSTRN01.svg

OBSTRN02.svg

OBSTRN03.svg

SPRING02.svg

UWTROC03.svg

WRECKS05.svg
[Symbols_with_Dots.zip](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/files/11367642/Symbols_with_Dots.zip)

The solution was to fill the 0.32 diameter circles with the pen color instead of drawing the perimeter of the circle.

The adjusted files are attached.

**Comment by DavidGrant-NIWC** [comment]
- [ ] Modify symbol metadata
    - per https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/92#issuecomment-1419718682
    - iho:publisher="IHO" vice "IHB"
    - iho:version="1.0" vice "0.1")
- [ ] Update affected symbols
- [ ] Notify PSWG to register updated symbols
