### ISSUE TITLE
[PSWG #126] Invalid display modes

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#234]
See NIWC actions https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/126#issuecomment-1552401124

**Comment by DavidGrant-NIWC** [comment]
Mariners objects are retained in version 1.2 of the PC pending discussions with IEC:
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/126#issuecomment-1758711055
