### ISSUE TITLE
[PSWG #125] Features with undefined portrayal

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#235]
See NIWC PC actions at https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/125#issuecomment-1553847438

- [x] 1. NIWC - Implement LandRegion Curve symbolisation similar to Surface with the featureName shown at the center.
- [ ] 2. NIWC - Implement RescueStation as per CoastGuardStation but using RSCSTA02 in the middle of the polygon.

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/2c580530-0025-4952-afc3-eac4759c8e55)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/74cf0e3a-ed02-42fa-a955-bbd6285d0e83)

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/b0132c35-070d-417e-9769-dc206e120b0b)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/7124a70f-1a92-4abe-aa7e-262c3e15a4a5)
