### ISSUE TITLE
Introduce color filled paper chart symbols for buoys and beacons [PSWG #117]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#238]
Review in entirety for PC updates.
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/117

**Comment by mikan66** [comment]
See commit [02ffd72](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/02ffd724ebc2aba4de043aa36a51e0e53e3b907d)

**Comment by DavidGrant-NIWC** [comment]
Need to re-implement top mark processing

**Comment by mikan66** [comment]
Reopened due to feature name changes like: BuoyCardinal to CardinalBuoy throughout in FC 1.2.0.

**Comment by mikan66** [comment]
Close this issue, covered under separate issue for general renaming of all such things.
