### ISSUE TITLE
LightAllAround : Confirms a lua condition

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#243]
Difficulties to interpret this lua condition : 
"local majorLight = feature.majorLight and feature.majorLight == 1 and not contains(categoryOfLight, { 5 }) **and not feature.rhythmOfLight** and feature.rhythmOfLight.lightCharacteristic and feature.rhythmOfLight.lightCharacteristic == 12 "

Proposal : local majorLight = feature.majorLight  and not contains(categoryOfLight, { 5 }) and feature.rhythmOfLight.lightCharacteristic == 12

Pol

**Comment by DavidGrant-NIWC** [comment]
See #60 

* Proposed check doesn't handle `rhythmOfLight == nil`
* Existing and proposed check don't handle morse code lights correctly
  * Existing check is missing parenthesis `and not (feature.rh... == 12)`
  * Proposed check should use `~= 12` vice `== 12`

Will update to:
```
local notAeroLight = not contains(categoryOfLight, { 5 })
local notMorseCodeLight = feature.rhythmOfLight == nil or feature.rhythmOfLight.lightCharacteristic ~= 12
local majorLight = feature.majorLight and notAeroLight and notMorseCodeLight
```

**Comment by plebihan29n** [comment]
Taking into account that for a lightallaround  the rythmOgLight is mandatory and lightCharacteristic is also mandatory inside a rythmOfRight , then => local notMorseCodeLight = feature.rhythmOfLight.lightCharacteristic ~= 12 **?**

**Comment by DavidGrant-NIWC** [comment]
* Mandatory attributes can be encoded as unknown.
  * The attribute is only truly mandatory if there is a specific check in S-58 to ensure it is present.
* Converted data may not populate mandatory attributes.
  * It also is not typically run through the S-58 checks.
* We have encountered test data where mandatory attributes are not populated.
  * You could argue that the data is bad and these objects should portray as "?" but doing that makes it more difficult to focus on other more pressing concerns.
*  In most cases there is no harm in checking to ensure the attribute is present.

If you would like to see missing mandatory attributes portray as "?" then it should be agreed upon within the PSWG.
