### ISSUE TITLE
OffshoreProductionArea : SymbolizedBoundaries

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#244]
Is it volunteer to portray this kind of Area with 'NAVARE51' ?
if not , proposal to replace 
 featurePortrayal:AddInstructions('LineInstruction:NAVARE51')
by
featurePortrayal:AddInstructions('LineInstruction:' .. symbol)
Pol

**Comment by DavidGrant-NIWC** [comment]
https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commits/main/PortrayalCatalog/Rules/OffshoreProductionArea.lua

Symbolized boundary:
1 - Wind Farm: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/68#issuecomment-1185208965
2 - Wave Farm: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/55#issuecomment-1185197139
3 - Current Farm: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/63#issuecomment-1185197537
4 - Tank Farm: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/54#issuecomment-1185206684
5 - SMEA: ?
6 - Solar Farm: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/67#issuecomment-1185201815

See the change history and related links to issues. I'm not sure whether the PSWG intended to change the default boundary symbolization from CTYARE51 to NAVARE51; will need @alvarosanuy and/or @mikan66 to chime in.

**Comment by alvarosanuy** [comment]
It was a deliberated decision to use CHGRD. This colour relates with the existence of physical obstructions within an area. All these farms contain multiple individual energy generators that, depending on scale, may or may not be fully individually charted.
