### ISSUE TITLE
OBSTRN7 : consistency with S-52

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#245]
Proposal to be consistent with S-52 : In the case of valueOfSounding <= contextParameters.SafetyDepth ,  for Line or Area 
replace the linestyle (dash',0.64,'CHBLK' ) by the linestyle (dash',0.64,'**CHGRD**' )

**Comment by DavidGrant-NIWC** [comment]
Note: change in appearance of wrecks is unrelated - see #232

|SafetyDepth=2|Result|
|:---:|:---:|
|Before|![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/a021cc3e-3d5d-42b1-b2fe-b3d10524bff9)|
|After|![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/61c70494-303e-407d-a63f-25322bab9d29)|
