### ISSUE TITLE
Lua Condition on Attribute Boolean

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#246]
Bonjour David
A request : Would be possible to replace the equal condition value of boolean by true/false in the place 1/0 ?
Pol

**Comment by DavidGrant-NIWC** [comment]
Please provide specific references. I agree boolean values should be checked for true/false rather than 1/0, but at a quick check through the catalog it appears booleans are being checked against true/false.

**Comment by plebihan29n** [comment]
David,
I have tried to detect == 0 or 1 for a boolean attribute in lua rules : 
the only case I have found => the attribute "visualProminence  == 1" used in many rules.
Pol

**Comment by DavidGrant-NIWC** [comment]
visualProminence is an enumeration:

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/0ba1addb-73ee-4515-972d-4138ea809427)
