### ISSUE TITLE
Additional Sounding Symbols : Proposal for definitions

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#248]
Here is a **proposal** to consistency and clarification for symbol definitions :

---Greater than safety depth
SOUNDGB1 : symbol for swept sounding, used for deep soundings greater than safety depth
SOUNDGC2 : **symbol for** sounding of low accuracy **, used for deep soundings greater than safety depth**

---Shallower than safety depth
SOUNDSA1 	symbol for drying height, used for shallow soundings, less than or equal to safety depth

SOUNDSB1   symbol for swept sounding, used for shallow soundings, less than or equal to safety depth

SOUNDSC3   **symbol for sounding of** low accuracy, **used for shallow soundings, less than or equal to safety depth**

**SOUNDSC2 "deprecated"**

**Comment by plebihan29n** [comment]
Correction:
SOUNDGC2 : symbol for sounding of low accuracy **, used for deep soundings greater than safety depth**

**Comment by DavidGrant-NIWC** [comment]
I think it's a good proposal, but:
* The current definitions should match the entries in the portrayal registry.
* If you would like to see them changed you would need to make a proposal to the PSWG or to the S-101PT.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/cef263da-3386-482c-8dde-7ea2306241f2)
