### ISSUE TITLE
LocalMagneticAnomaly : unknown valueOfLocalMagneticAnomaly

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#249]
In case of a LocalMagneticAnomaly has no valueOfLocalMagneticAnomaly (empty value because mandatory), the lua rule generate an error('Invalid primitive type or mariner settings passed to portrayal')

**proposal :** don't generate an error in order to keep the default symbolization taking account primitive type.

if magCount == 1 then
		if valueOfLocalMagneticAnomaly[1].magneticAnomalyValue ~= nil then
                   ......
               else 
                   => debug warning => no error
               end
end

the same for magCount == 2

Pol

**Comment by DavidGrant-NIWC** [comment]
Perhaps I'm misunderstanding, but if  `valueOfLocalMagneticAnomaly` == `{ nil }` then `magCount 
 = #valueOfLocalMagneticAnomaly` should evaluate as zero and the rule should return with no error generated?

**Comment by plebihan29n** [comment]
I have the following instance , that have a valueOfLocalMagneticAnomaly not nil but with a magneticAnomalyValue empty
the complex attribute valueOfLocalMagneticAnomaly is mandatory for the feature and  magneticAnomalyValue is mandatory for the complex attribute.
=> magCount==1 and magneticAnomalyValue is nill  

FeatureRecord
            Identifier featureType="LocalMagneticAnomaly" rcid="38" rcnm="100" ruin="insert" version="1"
            Foid 1810-29187676-1
            SimpleAttribute atin="insert" index="1" type="scaleMinimum" value="180000"
           **ComplexAttribute atin="insert" index="1" type="valueOfLocalMagneticAnomaly"
                SimpleAttribute atin="insert" index="1" type="magneticAnomalyValue" value=""
                SimpleAttribute atin="insert" index="1" type="referenceDirection" value=""
            ComplexAttribute**
            Curve ornt="forward" rrid="33" saui="insert"
    FeatureRecord

**Comment by DavidGrant-NIWC** [comment]
Thanks for the clarification.

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/e00482bf-9bdb-46ac-a08e-49149551739c)

* The mariner will have to pick the feature to get the information.
* `magCount` should never be two if the value is unknown.
