### ISSUE TITLE
ArchipelagicSeaLane : Surface has no representation

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#250]
Confirm that a ArchipelagicSeaLane type of surface has no representation (except cartographic text with name) .
related to #152

**Comment by DavidGrant-NIWC** [comment]
See [PSWG issue 80](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/80)

**Comment by plebihan29n** [comment]
yes I have read the issue 80 and I understand it concerns ArchipelagicSeaLane **with no geometr**y. Here i have the case of an **area** instance and no representation appears , is it really the objective ?

**Comment by DavidGrant-NIWC** [comment]
The area is present only to support the placement of a label. This is the case with most of the "noGeometry" features which are aggregations of other features (range system, island group, etc.)
