### ISSUE TITLE
Buoy Emergency Wreck Marking

### ISSUE THREAD

**Issue by TomRichardson6** [iho-ohi/S-101_Portrayal-Catalogue#258]
When viewing a Buoy Emergency Wreck Marking feature it displays with the simplified symbol whether simplified or paper chart symbols are selected. Unlike other buoys and beacons the rule file does not seem to contain the associated context parameter in its logic or the required clauses to show the paper chart symbols. 

ShoreECDIS version 1.3.0.0 June 06, 2023, Portrayal Catalogue 1.1.2 DRAFT, Test Dataset DS0020 Edition 3 

https://github.com/iho-ohi/S-101_Portrayal-Catalogue/blob/main/PortrayalCatalog/Rules/BuoyEmergencyWreckMarking.lua

**Comment by DavidGrant-NIWC** [comment]
Per [PSWG Issue #46](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/46#issuecomment-1182759366) the same symbol is to be used from both Simplified and Traditional symbol sets.
