### ISSUE TITLE
PortrayalCatalog/ViewingGroupLayers/10 Miscellaneous (Standard)

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#259]
The ViewingGroupLayer "10 (Miscellaneous (Standard))" is defined with the same viewing groups as 10a (Miscellaneous chart Standard Display elements) and 10b (Toggles graphical highlighting of detected alerts).
This could lead to confusion when these layers (10,10a,10b) will be set to visible/invisible ?
I propose for clarification to remove The ViewingGroupLayer "10 (Miscellaneous (Standard))" and keep the two separate layers (10a and 10b)

**Comment by DavidGrant-NIWC** [comment]
There is no restriction in S-100 on the number of viewing group layers which may contain a given viewing group. This concept is actually carried forward from S-52, see the pic below from S-52 PresLib 4.0.3 noting viewing group layer 3, 3.1, and 3.2. Logically, layers which share a viewing group must participate in a common display mode (base/std/other/none). 

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/96f7645f-0f53-4c93-bcd4-642abae0ebb9)

If you'd like to see the layers changed, please create an issue in the PSWG repo: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues. Issues here should relate to errors or omissions in the PC implementation, or to implementation of changes approved by the PSWG.
