### ISSUE TITLE
Precision of numeric values in light descriptions and labels on dredged areas

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#262]
When the EncodeString is called with the format "0.1f" (for example) and the "str" variable is an integer , if possible it could be preferable to display this variable as an integer and **not** as a float.

Example in the  DredgedArea.lua , the area above has a 12m for "depthRangeMinimumValue" and the text instruction generate a "12.0m"

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/24851994/f05e81f9-1ee7-4dfc-b7c4-003abad08569)

I have updated the lua rule as follow but I presume there is a best way to do that

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/24851994/c26e670a-8452-45fe-9204-c3142e977d81)

This is also true for text instructions generated from LITDSN02

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/24851994/8e185ea3-0b95-41fd-9ad2-0b6df008eac3)

**Comment by DavidGrant-NIWC** [comment]
Excerpt from S-52 PresLib 4.0.3 10.6.3:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/cc3551be-ea55-4f6c-b279-0561d97a3757)

**Comment by DavidGrant-NIWC** [comment]
Will use %g formatting. LITDSN has already been changed.

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/90f3e59e-0255-4e50-8a41-9f4b61680fe3)
