### ISSUE TITLE
Deal with Incomplete "PeriodicDateRange"

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101_Portrayal-Catalogue#263]
When a feature supports the complex attribute "PeriodicDateRange" and for which either the date start, either the date end, is not set (despite the fact that they are mandatory), the global lua "main" rule fails  . 

My proposal is to update the function "ProcessPeriodicDateRanges" as :

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/24851994/884645e3-5782-42d7-9de1-40a764a3a913)

Pol

**Comment by DavidGrant-NIWC** [comment]
This is an error in the data and should be detected by a validation check. It doesn't make sense to have a periodic date range without both a start and end date.

The issue should be raised with the S-101 validation group if there is not already a check for this.

**Comment by TomRichardson6** [comment]
Agree with @DavidGrant-NIWC @plebihan29n can you confirm which cell this applies to? I will validate and check this there are a number of validation checks that should detect date related issues.

**Comment by plebihan29n** [comment]
The cell concerns is a S-158 cell issue from the conversion of S-58 errors. The S-58 cell is A4000004 and the original error is highlight below :
![periodicDate](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/24851994/64e6bdf7-1ef4-4d8e-bec9-85e2472ce084)

The original cases from s-57 , once converted in s-158 logically must raise the following warnings :
- 5_007 => Attribut Format ....
- 5_005 => Attribut Multiplicity ..

**Comment by DavidGrant-NIWC** [comment]
When this occurs, the portrayal will ignore the incomplete `periodicDateRange` but will still add a date dependent symbol. A warning will also be output via a Debug.Trace statement:

_Warning: feature|136 has incomplete periodicDateRange_
