### ISSUE TITLE
BOYSPP35 disagrees with S-52

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#265]
Location of black point differs.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/5908c797-c358-4581-94a2-c3e313d48d79)
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/b464be4a-9edc-46c5-9534-778b9e03638b)

**Comment by alvarosanuy** [comment]
Please make sure that whenever an SVG files is modified by NIWC, new versions are shared with me so I can update existing entries in the GI Registry.

**Comment by mikan66** [comment]
@DavidGrant-NIWC, please review symbol.  I used the latest IHO symbol editor, but had to manually tweak the output file in several places, including color fill, to get this picture. 
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/2a63897d-6183-4b57-879c-84f6fb33028e)
![BOYSPP35_shift](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/7f4e8e0c-6e96-4ea4-b737-87f83e8542e7)

**Comment by mikan66** [comment]
@alvarosanuy, sending you an updated file via email attachment.

**Comment by mikan66** [comment]
Confirmed file was transferred to Alvaro.
