### ISSUE TITLE
BOYLAT34 incorrect viewbox

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#266]
Clipped

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/b1a66dd7-7400-44f9-a956-b59e6a71df1b)

**Comment by mikan66** [comment]
@DavidGrant-NIWC , This looks OBE due to new symbols for buoys.  Recommend we remove from catalog and close this as no rules invoke this symbol.

**Comment by mikan66** [comment]
Removed from catalog. Commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/12b6f42f95a15935446e3b4a76f4ca74f4a7aaa9
