### ISSUE TITLE
Change name of viewing group 28010 to add pilotage district.

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#268]
See [PSWG 147](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/147)

**Comment by mikan66** [comment]
Updated, see commit [cebd41e](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/cebd41ed42a0d52701c31ce6dcd2b4fdae2eab19)
