### ISSUE TITLE
VirtualAISAidToNavigation is using viewing group `21010`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#270]
Viewing group `21010` is reserved for unknown objects (the `?` symbol).

**Comment by mikan66** [comment]
Use 27240, see PSWG #70 and #37.

**Comment by mikan66** [comment]
See commit [0e3d9a0](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/0e3d9a04df12df22aef416611d55db57e23366ae)
