### ISSUE TITLE
emergency wreck marking buoy (EWMB) [PSWG #117]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#276]
Separately address this specification for EWMB as subset of PSWG #117.

Amend EWMB Rule and use the new 'Simplified' symbol BOYNDM02 to represent its 'Simplified' symbol. (ZIP file in Mikus comment above). Remove symbol BOYNDM01 from the PC.

Symbol location: https://github.com/S-101-Portrayal-subWG/Working-Documents/files/13278826/BOYNDM02.zip

**Comment by mikan66** [comment]
See commit [6fe9808](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/6fe98086e1f0ca22a8b1b917ea2c00f3c5711c4b).  Always as this: 
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/555a4ca1-b81b-4f2f-bcc8-42976239f52a)

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/b725ddbf-9e74-4c53-b447-e3592157491d)

**Comment by mikan66** [comment]
see commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/ded60d49305dc72c8be1c68fa8814ffb5a3e1718.  Needs final test with FC and data.
