### ISSUE TITLE
Amend `DockArea` to remove color fill [PSWG #98]

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#279]
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/98#issuecomment-1771894244

https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/98#issuecomment-1763574468

Dock area is obscuring underlying features such as `DepthArea` and the shallow water pattern. The PSWG has directed removal of the color fill.

**Comment by DavidGrant-NIWC** [comment]
#### Before
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/5d629388-15f2-47fb-a74a-04588e082f86)

#### After
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/6586595d-bc26-4ee3-b9a1-dab7501fad04)

**Comment by mikan66** [comment]
Re-evaluate for closure based on latest comments here: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/98#issuecomment-1825439111

**Comment by DavidGrant-NIWC** [comment]
Marked invalid based on https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/98#issuecomment-1825439111

**Comment by DavidGrant-NIWC** [comment]
Need to revert removal of color fill:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/26f3056f-f197-474b-8b7a-3b4e60bd37e5)

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/8fcba881-e9f0-4d06-9ca2-1d71b05a847a)
