### ISSUE TITLE
`TextInstruction` requires a `FontColor` text style command

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#280]
Some rules are missing a `FontColor` text style command prior to issuing a `TextInstruction` drawing command. Part 9a does not provide a default token value for `TextInstruction`:

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/e840fdf9-b6dd-4075-8706-0d2b1c49762c)

#### Affected Rules
- [x] Berth (DS8)
- [x] Bridge (DS6)
- [x] Building (DS6)
- [x] BuiltUpArea (DS6)
- [x] CableOverhead (DS6)
- [x] Conveyor (DS6)
- [x] DockArea (DS8)
- [x] LandArea (DS6)
- [x] LandElevation (DS5)
- [x] LandRegion (DS5)
- [x] MagneticVariation.lua (DS4)
- [x] PipelineOverhead (DS6)
- [x] SeaAreaNamedWaterArea (DS3, DS4)

To check: DS10+

**Comment by DavidGrant-NIWC** [comment]
- [ ] CurrentNonGravitational (DS10)
- [ ] DeepWaterRouteCentreline (DS15)
- [ ] DredgedArea (DS11)
- [ ] Fairway (DS15)
- [ ] NavigationLine (DS15)
- [ ] OffshorePlatform (DS14)
- [ ] RadioCallingInPoint (DS15)
- [ ] RecommendedRouteCentreline (DS15)
- [ ] RecommendedTrack (DS15)
- [ ] SweptArea (DS11)
- [ ] TidalStreamFloodEbb (DS10)

To check: DS16+

**Comment by DavidGrant-NIWC** [comment]
- [ ] AnchorageArea (DS16)
- [ ] BeaconSpecialPurposeGeneral (DS23)
- [ ] BuoyLateral (DS23)
- [ ] FogSignal (DS20)
- [ ] LightVessel (DS20)
- [ ] PilotBoardingPlace (DS22)

**Comment by DavidGrant-NIWC** [comment]
Potentially affected rules with no supporting test data:

gci -File | Where-Object { ( $_ | Select-String "AddTextInstruction" -quiet) -and !( $_ | Select-String "CHBLK" -quiet) }

- [ ] AnchorBerth
- [ ] ArchipelagicSeaLane
- [ ] BeaconCardinal
- [ ] BeaconIsolatedDanger
- [x] BeaconLateral
- [ ] BeaconSafeWater
- [ ] BuoyCardinal
- [ ] BuoyEmergencyWreckMarking
- [ ] BuoyInstallation
- [ ] BuoyIsolatedDanger
- [ ] BuoySafeWater
- [ ] BuoySpecialPurposeGeneral
- [ ] Daymark
- [ ] DeepWaterRoute
- [ ] FairwaySystem
- [ ] IslandGroup
- [ ] LightFloat
- [ ] MooringTrot
- [ ] RadarLine
- [ ] RadarStation
- [ ] RangeSystem
- [ ] Tideway
- [ ] TrafficSeparationScheme
- [ ] TrafficSeparationSchemeLanePart
- [ ] TwoWayRoute
- [ ] VesselTrafficServiceArea

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/c3f93d70-11fc-45dd-8a45-571223c8127c)

**Comment by TDYCARHugh** [comment]
Here are the text style default and common styles I used in the XSL S-101 portrayal where I wrote a style template/function to populate simple text styles which were used in S-52.

`   
 
    <xsl:template name="textStyle">
	<xsl:param name="style"  select="default"/> 

		<xsl:choose>
			<xsl:when test="$style = 'default'">
				<xsl:element name="bodySize">10</xsl:element>				
				<xsl:element name="foreground">CHBLK</xsl:element>				
				<xsl:element name="fontCharacteristics"> 
					<xsl:element name="weight">Medium</xsl:element>				
					<xsl:element name="slant">Upright</xsl:element> 				
					<xsl:element name="serifs">0</xsl:element> 				
					<xsl:element name="proportion">MonoSpaced</xsl:element>			
				</xsl:element>				
			</xsl:when>
			<xsl:when test="$style = 'Italics'"> 
				<xsl:element name="bodySize">10</xsl:element>				
				<xsl:element name="foreground">CHBLK</xsl:element>				
				<xsl:element name="fontCharacteristics"> 
					<xsl:element name="weight">Medium</xsl:element>				
					<xsl:element name="slant">Italics</xsl:element> 				
					<xsl:element name="serifs">0</xsl:element> 				
					<xsl:element name="proportion">MonoSpaced</xsl:element>			
				</xsl:element>				
			</xsl:when>
			<xsl:when test="$style = 'Light'">  
				<xsl:element name="bodySize">10</xsl:element>				
				<xsl:element name="foreground">CHBLK</xsl:element>				
				<xsl:element name="fontCharacteristics"> 
					<xsl:element name="weight">Light</xsl:element>				
					<xsl:element name="slant">Upright</xsl:element> 				
					<xsl:element name="serifs">0</xsl:element> 				
					<xsl:element name="proportion">MonoSpaced</xsl:element>			
				</xsl:element>				
			</xsl:when>
			<xsl:when test="$style = 'Magenta'">  
				<xsl:element name="bodySize">10</xsl:element>				
				<xsl:element name="foreground">CHMGD</xsl:element>				
				<xsl:element name="fontCharacteristics"> 
					<xsl:element name="weight">Medium</xsl:element>				
					<xsl:element name="slant">Upright</xsl:element> 				
					<xsl:element name="serifs">0</xsl:element> 				
					<xsl:element name="proportion">MonoSpaced</xsl:element>			
				</xsl:element>				
			</xsl:when>
			<xsl:when test="$style = 'LightMagenta'">  
				<xsl:element name="bodySize">10</xsl:element>				
				<xsl:element name="foreground">CHMGD</xsl:element>				
				<xsl:element name="fontCharacteristics"> 
					<xsl:element name="weight">Light</xsl:element>				
					<xsl:element name="slant">Upright</xsl:element> 				
					<xsl:element name="serifs">0</xsl:element> 				
					<xsl:element name="proportion">MonoSpaced</xsl:element>			
				</xsl:element>				
			</xsl:when>
			<xsl:when test="$style = 'LightMagentaFaint'">  
				<xsl:element name="bodySize">10</xsl:element>				
				<xsl:element name="foreground">CHMGF</xsl:element>				
				<xsl:element name="fontCharacteristics"> 
					<xsl:element name="weight">Light</xsl:element>				
					<xsl:element name="slant">Upright</xsl:element> 				
					<xsl:element name="serifs">0</xsl:element> 				
					<xsl:element name="proportion">MonoSpaced</xsl:element>			
				</xsl:element>				
			</xsl:when>
			<xsl:otherwise>
				<xsl:text>error:unrecogonized text style parameter:</xsl:text> <xsl:value-of select="$style"/>
			</xsl:otherwise>
		</xsl:choose>
	
				
	
    </xsl:template>
`

**Comment by DavidGrant-NIWC** [comment]
About half-way through making these hundreds of changes it did occur to me that I should have just set a default global variable... It could internally keep track of most of the state variables to minimize the number of state commands it outputs. Oh well, something to consider if we ever get around to optimizations.
