### ISSUE TITLE
Local Magnetic Anomaly - Portrayal of Curves & Surfaces [PSWG #148]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#283]
Review final status based on PSWG notes.
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/148#issuecomment-1819763186

**Comment by DavidGrant-NIWC** [comment]
Closed based on https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/148#issuecomment-1820089902

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/a6b4cbe5-a9dc-4858-959a-693eb6c616cb)
