### ISSUE TITLE
QoBD should evaluate depth range [PSWG #127]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#285]
Evaluate issues status in PSWG github

**Comment by DavidGrant-NIWC** [comment]
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/127

**Comment by DavidGrant-NIWC** [comment]
Needs supporting test data to validate implementation. See https://github.com/iho-ohi/S-101-Test-Datasets/issues/48
