### ISSUE TITLE
Add support for S-101 TextPlacement feature

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#3]
See [Portrayal sub-group issue](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/29)

* [ ] Verify portrayal and DCEG sub-group approval of model changes (S-101PT)
* [ ] Verify updated S-101 FC if needed
* [ ] Verify updated S-100 portrayal schemas if needed (S-100WG6)
* [ ] Update PC
* [ ] Produce supporting test data
* [ ] Verify implementation

**Comment by mikan66** [comment]
@DavidGrant-NIWC Please review https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/29 and decide on status of this issue to remain open or closed.

**Comment by DavidGrant-NIWC** [comment]
awaiting test data - defered to 1.2.0 or later

**Comment by DavidGrant-NIWC** [comment]
Preliminary data:
https://github.com/iho-ohi/S-164-Sub-Group/issues/69#issuecomment-1934566075

**Comment by DavidGrant-NIWC** [comment]
**Note: the current modeling doesn't support overriding the light description.**

|Test|Result (North up)|
|:---|:---:|
|Change placement of light description.<br/><br/>Note: rotation is not implemented yet; see #303|![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/c7dc71d8-445f-44f4-8fa4-587063a10ec6)|
|Change placement of feature name.|![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/3ebf0e68-d076-4d0b-b3fc-634db0648b6d)|
|Override feature name and specify placement.|![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/149fbe9b-cd9b-471e-9767-67a68f488d5f)|

Screen Cap (East Up)
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/01966049-be80-454d-9a40-888538556634)
