### ISSUE TITLE
Marine Pollution Regulations Area (row 15 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#30]
20220422_S101 Portrayal_Consolidation of pending actions.xlsx

![image](https://user-images.githubusercontent.com/4913543/165263201-d13e8738-07aa-4e2d-ba99-2ecfd0670929.png)

- [ ] Marine Pollution Regulations Area (new rule)

**Comment by mikan66** [comment]
See https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/74.  #74 takes priority over #23, but see note in spreadsheet (row 15 main).

**Comment by mikan66** [comment]
See https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/74#issuecomment-1190925642

**Comment by mikan66** [comment]
commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/ae45e2ab510b28a57291c5da1123c483b938dee4

**Comment by mikan66** [comment]
Need to add MARPOL to Viewing Group Layer 18 in Portrayal Catalog.

**Comment by mikan66** [comment]
Marine Pollution Regulations Area added to Viewing Group Layer 18 (Miscellaneous)
See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/58de0691fdf451ef2aa073332e490979c0c461fd

**Comment by DavidGrant-NIWC** [comment]
|Plain Boundaries|Symbolized Boundaries|
|:---:|:---:|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/09d321c2-7e56-4d90-9250-7e70cf653761)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/9db39370-af3b-458b-b7d9-8d23c8ecd2d3)
