### ISSUE TITLE
Add textRotation to the TextPlacement feature (Gap analysis 19OCT23 Row C) 

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#303]
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/153#issuecomment-1769765446

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/846d6ca6-e254-4142-a739-222416a04513)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/a1ef90b5-8478-4066-a7d4-19f529fd0aed)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/e196be5c-4ae4-4c7c-bec1-dc66744e45c7)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/695934b3-c8f5-4d2b-96d4-d0b2f2c7cd0d)

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/0225b677-6e7b-44ca-a0af-9d9bcfde85be)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/22530c6e-f514-4598-8e97-ceb57a5bc40a)
