### ISSUE TITLE
Bridge re-modelled (former) attribute category of bridge (Gap analysis 19OCT23 Row 25)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#306]
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/153#issuecomment-1769765446

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/d4602e0b-cb08-4a32-b096-e2db09605ecb)

DCEG 1.2.0: Clause 6.6 Bridge

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/9c80826b-1f63-431e-b40c-4726d392431e)

**Comment by alvarosanuy** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/70189016/0d32bc50-5cb5-4cf8-b7eb-0d7ad3bb5965)

**Comment by mikan66** [comment]
PC 1.1.n has separate processing, (portrayal) for:  
Curves & Surfaces: feature.categoryOfBridge == 2,3,4,5,7,8, else default for (9,10,11,12)

I can map 2,3,4,5,7 to "categoryOfOpeningBridge" if "openingBridge" is True.
old 8 now maps to "bridgeConstruction" = 5 or does old PC 8 have a different meaning than new "bridgeConstruction" = 5? 

Old 9, 10, 11, 12 appear to just remain as DEFAULT processing regardless of new "openingBridge", or something else?

**Comment by alvarosanuy** [comment]
Data producers must encode **openingBridge** when bridges are over navigable water.

**Very simplistically, I think the general new logic to apply should be:**

1) Bridge **is** over navigable water:

A) When **openingBridge**= True - we have to depict the 'thick black line' symbology with the 2 magenta concentric circles (in the middle of the curve or center of the Surface).
B) When **openingBridge** = False - same as above but without the magenta circles.
In both cases, text for clearance values should be added as appropiate (i.e. clr // clr cl and/or clr op).

2) Bridge **is not** over navigable water:

Data producers are not required to encode **openingBridge**. 
If  **openingBridge** is not populated or equal to False - Use the symbology for Fixed bridges [1) B)], as a simplified depiction of Bridges in an area not open for navigation.
If producers decide to encode **openingBridge** = True, their symbology should follow guidance in [1) A)] above.
Depict 'clearances' if encoded.
