### ISSUE TITLE
Hierarchy of metadata (Gap analysis 19OCT23 Row M)

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#314]
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/153#issuecomment-1769765446

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/b25cd8a1-3799-4ded-8a5f-dedb14a1c338)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/3fafe103-542c-4344-9f3a-1028711a1958)

**Comment by DavidGrant-NIWC** [comment]
Attribute usage within current portrayal rules:

|Attribute|Rule(s)|Hierarchical evaluation needed?| 
|:---|:---|:---|
|`marksNavigationalSystemOf`|LocalDirectionOfBuoyage|No|
|`horizontalPositionUncertainty`|None|No
|`verticalUncertainty`|None|No
|`horizontalDistanceUncertainty`|None|No
|`horizontalPositionUncertainty`|None|No
|`orientationUncertainty`|None|No
|`verticalUncertainty`|None|No
|`qualityOfHorizontalMeasurement`|DEPARE03, DEPCNT03, OBSTRN07, QUALIN02, QUAPNT02, SLCONS04, SNDFRM04, WRECKS05|TBD
|`qualityOfVerticalMeasurement`|SNDFRM04|TBD
|`techniqueOfVerticalMeasurement`|SNDFRM04|TBD
|`verticalDatum`|None|No

@alvarosanuy - the buoy symbol is selected based on the color attribute(s) (R,G,R or G,R,G) not based on the system of marks so I don't think that meta-feature requires evaluation within the portrayal rules.

**Comment by DavidGrant-NIWC** [comment]
### SNDFRM04 - Symbolization of depth values.

Called from:
DepthNoBottomFound, OBSTRN07, SOUNDG03, WRECKS05

Evaluates:

|Attribute|On Feature|On Spatial Quality|On Meta-Feature|Purpose|
|:---|:---:|:---:|:---:|:---|
|`techniqueOfVerticalMeasurement`|Yes|N/A|`QualityOfSurvey`|Determine whether to add swept sounding symbol|
|`qualityOfVerticalMeasurement`|Yes|N/A|`QualityOfSurvey`|Determine whether to add low accuracy symbol ring|
|`qualityOfHorizontalMeasurement`|N/A|Yes|`QualityOfSurvey`|Determine whether to add low accuracy symbol ring|

#### Implementation
* If attribute does not have a value (including `unknown`) on the feature or the `SpatialQuality`
  * Find all `QualityOfSurvey` geometries which intersect the feature.
    * For soundings, if any point intersects then the features intersect.
  * Does depth of object fall within `depthRangeMinimum` and `depthRangeMaximum` of the `QualityOfSurvey`?
    * Get attribute value from `QualityOfSurvey`

**Comment by DavidGrant-NIWC** [comment]
@jeffwootton @alvarosanuy @tomrichardson6 @TDYCARHugh

I don't think this is going to do what you want. I can't evaluate individual sounding points, I can only check each group of soundings against the geometry of each `QualityOfSurvey` object. This means that every point associated with a `Sounding` feature must lie within a single `QualityOfSurvey` feature (or have no overlapping `QualityOfSurvey`).

This begs the question of why the production system doesn't just copy the attributes from the `QualityOfSurvey` onto the individual features / `SpatialQuality`?

Alternatively, you could add a cartographic attribute to indicate the soundings are low accuracy and/or swept. Again, the production system should be able to populate this automatically.

In the meantime, I'll continue with the implementation of the spatial evaluation, but I don't have any test data.

**Comment by DavidGrant-NIWC** [comment]
* No optimizations
* Using QoBD as a proxy for QoS
  * Soundings not in a CATZOC A1 area are drawn with circle and underbar

This change makes the portrayal about 600% slower per dataset (from ~300ms to ~1850ms for a single dataset). I only have a single dataset to test with, so this is a very rough measurement. However, performance will only degrade further because I've only implemented the processing for soundings.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/1e3f8521-5d45-41ee-a12c-e96495ef45fe)

**Comment by alvarosanuy** [comment]
> @alvarosanuy - the buoy symbol is selected based on the color attribute(s) (R,G,R or G,R,G) not based on the system of marks so I don't think that meta-feature requires evaluation within the portrayal rules.

Noted

**Comment by DavidGrant-NIWC** [comment]
See: https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/153

**Comment by DavidGrant-NIWC** [comment]
Note that spatial quality may degrade over time; the implementation must handle multiple `SpatialQuality` instances with different date ranges.

https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/362
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/25270a4c-bd45-4727-8f95-aeca638084b3)

**Comment by DavidGrant-NIWC** [comment]
Moved here from #363; note for implementation:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/94f6ee0f-bc87-4c1b-9d3a-976536f71f4e)

**Comment by DavidGrant-NIWC** [comment]
Per conversation with @JeffWootton, these three rows will be removed from the table as the attributes don't inherit values from QoS:

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/8beea581-e6ad-4586-a244-46a05613f0e5)

**Comment by alvarosanuy** [comment]
**Silly question:**

Why is required to spatially evaluate geo features against Meta features when the end result is not going to affect Portrayal or the triggering of Alerts?
In the M_NSYS case, why is so important to determine the category of the system of marks a navaid is based on if that info is not going to be used by the PC (even if there are different values encoded in the geo and the meta features). It seems like an unnecessary use of computing power ..
Same applies to QoNBD - at the moment, irrespective of the prevalent value (Meta or Geo) ECDIS is not expected to do anything with that info (e.g create buffer zones and either present them top the mariners or influence Alerts). I know the use of accuracies on non-bathymetric features could be introduced based on new MSC.530 requirements but I hope our practical interpretation restrict those broad requirements to QoBD and hydrographically relevant features only.

I hope the Table is just a graphical presentation of Hierarchical relationships between Geo and Meta values and not an OEM requirement to continually evaluate (compute) the prevalent attribute value for each impacted feature when the result won't be of use ... Today, the only use case for me is for the uncertainties of hydrographically relevant features (QoBD).

**Comment by DavidGrant-NIWC** [comment]
The table is necessary so that encoders and implementers understand how these attribute values are determined/populated. 

Agree that currently it isn't necessary to perform spatial evaluation since none of these attributes are evaluated by the current portrayal. This is reflected in my comment above, the last column indicates the attributes use within portrayal (shown below).

My main concern in this issue for PC 1.3 was the evaluation of the three attributes inherited from QoS for application to the low accuracy ring and symbolization of approximate points and curves. Jeff's update to the table should remove this concern and eliminated the need for spatial evaluation when portraying those elements.

> Today, the only use case for me is for the uncertainties of hydrographically relevant features (QoBD).

Agree, and the need for spatial evaluation even in that case could be removed if the DCEG is updated to always require spatial quality be associated to the geometry of features which are evaluated by alerts.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/ab92a953-49c5-497c-88dd-e838fda22c56)

**Comment by alvarosanuy** [comment]
> The table is necessary so that encoders and implementers understand how these attribute values are determined/populated.

Shouldn't the table also include:

-  **VerticaDatumOfData - verticalDatum** (Meta) & **verticalDatum** (Geo)
-  **SoundingDatum - verticalDatum** (Meta) & **verticalDatum** (Geo)

maybe others? I haven't done a thorough cehck.

**Comment by DavidGrant-NIWC** [comment]
> Shouldn't the table also include:
> * **VerticaDatumOfData - verticalDatum** (Meta) & **verticalDatum** (Geo)
> * **SoundingDatum - verticalDatum** (Meta) & **verticalDatum** (Geo)

`VerticalDatumOfData` is the last row of the table:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/9ffb6bf5-ed2f-42f3-9924-c9b8982603fa)

I don't believe there is any way to override the `SoundingDatum`. As far as I can tell, `verticalDatum` on a feature always overrides the `VerticalDatumOfData`. I think there is still ambiguity in the modeling regarding which attributes the `verticalDatum` applies to, and have previously proposed that the `verticalDatum` attribute be part of complex attributes that include the values to which it applies. Something like:

* verticalClearance
  * verticalClearanceValue
  * verticalUncertainty
  * verticalDatum

* height
  * heightValue
  * verticalDatum

etc.

With respect to this issue, the portrayal doesn't evaluate any of the datums, but this could become an issue if we want to alert on clearances.

**Comment by alvarosanuy** [comment]
**Can we close this Issue as 'Implemented in PC 1.3.0'?** As far as I understand, all elements to enable the correct attribution of Hydrographic features' Uncertainties are in place. All other entries in the table do not require hierarchical evaluations at this point in time.

**Comment by DavidGrant-NIWC** [comment]
> As far as I understand, all elements to enable the correct attribution of Hydrographic features' Uncertainties are in place.

The inheritance of uncertainties has been prototyped for soundings; presumably that implementation will also work for other isolated dangers with point geometries. The solution for curves and especially surfaces is undefined. Note that the DCEG prohibits `SpatialQuality` to be associated with surface geometries.

This issue is targeted at PC 1.4 because we are awaiting the S-101 alert requirements necessary to meet MSC.530. We may or may not need to implement inheritance to meet those requirements; it depends on whether (or how) the DCEG / encoding requirements are changed.

**Comment by alvarosanuy** [comment]
> The inheritance of uncertainties is not in the current PC. It has been prototyped for soundings but is not included in the current catalog. Presumably the prototype implementation will also work for other isolated dangers with point geometries. The solution for curves and especially surfaces is undefined. Note that the DCEG prohibits `SpatialQuality` to be associated with surface geometries.
> 
> This issue is targeted at PC 1.4 because we are awaiting the S-101 alert requirements necessary to meet MSC.530. We may or may not need to implement inheritance to meet those requirements; it depends on whether (or how) the DCEG / encoding requirements are changed.

**Noted, Thanks.**

**Comment by DavidGrant-NIWC** [comment]
> This issue is targeted at PC 1.4 because we are awaiting the S-101 alert requirements necessary to meet MSC.530. We may or may not need to implement inheritance to meet those requirements; it depends on whether (or how) the DCEG / encoding requirements are changed.

Direction is that portrayal will not be responsible for applying accuracy to alerts. This will become an OEM responsibility and direction will be provided in S-98 Annex C.

Closing as OBE
