### ISSUE TITLE
Incorporate new EWMB 'Paper Chart' symbols [PSWG #158]

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#316]
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/158

- [x] Incorporate new version of the EWMB 'Paper Chart' symbol BOYSHP60 (to show slanted color bands)
- Incorporate new EWMB 'Paper Chart' symbol for 'Pilar' & 'Spar' buoy shapes
  - [x] ![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/61284506-6459-4c80-92b7-8449025ffebb)
  - [x] ![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/459c3c8e-5503-46b2-89f3-cb26137be4af)
  - [x] Update rules to use new symbols

**Comment by mikan66** [comment]
Decision APR 9, 2024:  https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/158#issuecomment-2049006533

**Comment by mikan66** [comment]
Cleaned up, but will leave open until final decision on BOYSPR60.  https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/919d693d8effb81e521632d739da5547502ba07f

**Comment by DavidGrant-NIWC** [comment]
@alvarosaynuy

Are you ok with removal of these symbols? They are currently unreferenced by any rule:

|Symbol|Description|History|
|:---:|:---|:---|
|`BCNTOW60`|beacon tower, emergency wreck mark, paper-chart. Believe this was added with the color filled nav aid symbols, but the rules were never updated to reference it.|[BCNTOW60](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commits/main/PortrayalCatalog/Symbols/BCNTOW60.svg)|
|`BOYNDM02`|old version of EWMB (simplified)?|[BOYNDM02](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commits/main/PortrayalCatalog/Symbols/BOYNDM02.svg)|
|`BOYSPP45`|old version of EWMB?|[BOYSPP45](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commits/main/PortrayalCatalog/Symbols/BOYSPP45.svg)|

**Comment by DavidGrant-NIWC** [comment]
- [x] Removed BCNTOW60 and BOYSPP45
- [x] Added portrayal of topmark
- [x] Use BOYNDM02 when simplified symbols are enabled

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/f62d71e4-c94e-4be2-ae36-d6273c49bf2b)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/61a98f2d-bed3-4462-ba6e-f83962488967)
