### ISSUE TITLE
Update symbol `BOYSHP50` (Safe Water 'Paper Chart' symbol), `BOYSPH60`, `BOYSPR60` and `BOYPIL60`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#317]
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/158

Update symbol once created (slanted color bands)

**Comment by DavidGrant-NIWC** [comment]
Symbols are available: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/158#issuecomment-2025057738

**Comment by DavidGrant-NIWC** [comment]
Ensure metadata, CSS reference, etc. are correct during update.

**Comment by mikan66** [comment]
Essentially duplicate of 316.
