### ISSUE TITLE
`UpdateInformation` with `updateType`=`4` (move) is only partially implemented.

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#331]
It currently shows a delete symbol at the location of the `UpdateInformation` spatial object. We need clarification on how this will be encoded and the desired chart appearance in order to complete the implementation.

**Comment by mikan66** [comment]
spec update: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/151#issuecomment-2050808960

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/d0909e55-b922-4f62-a2b1-0f30fac01d6b)
