### ISSUE TITLE
Remove converter comments from rule files [PSWG #143]

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#340]
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/143

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/a93abafd-2336-45e0-a8d2-91914f987f64)

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/de1fffdf1816a90ed387ff8148e1b8d9d4d7e3be
