### ISSUE TITLE
S-101 PC v1.2 does not load in Shore ECDIS

### ISSUE THREAD

**Issue by MikusRL** [iho-ohi/S-101_Portrayal-Catalogue#343]
Do I need to do something prior I can load the new version in Shore ECDIS (v.1.4.0.0)? It does not allow to load it in:

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/72803214/3bb84983-d42f-40af-b865-09c9d83fa30d)

**Comment by MikusRL** [comment]
@DavidGrant-NIWC @mikan66  Have I missed a new Shore ECDIS version? On IHO GI Registry 1.4.0.0 is the latest. Thanks.

**Comment by MikusRL** [comment]
I have a PC catalog draft 1.2 version from 19. January downloaded from the IHO GitHub, and that loads fine in the Shore ECDIS.

**Comment by mikan66** [comment]
We have to prepare a NEW release of the Shore ECDIS.  The PC schema changes modified the SENC structure.  Although the S100Viewer does not use a SENC, it too will require an update resulting from the new PC schema changes to 5.1.

**Comment by MikusRL** [comment]
I will then close this issue and wait for the update to Shore ECDIS. Thanks.

**Comment by mikan66** [comment]
New NIWC Testbed has been posted to https://registry.iho.int/repository/list.do
