### ISSUE TITLE
Remove `svg` from CSS files

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#345]
The day CSS file defines an `svg` class which is unreferenced. The dusk and night CSS files attempt to apply a default background and foreground color to all the SVG's, probably to aid in viewing within the browser or an SVG editor.

The entries should be removed from all the files since we don't want these colors applied when rendered on ECDIS.

**Comment by mikan66** [comment]
Commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/d34cf94e488788c2a01b23f0c71a8246f7e69cd8
