### ISSUE TITLE
SVG <fileName> duplication

### ISSUE THREAD

**Issue by gorogara** [iho-ohi/S-101_Portrayal-Catalogue#348]
Second "BOYCON30.svg" should be changed to "BOYCON31.svg"

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/5345308/6edd11f0-bd20-48eb-ad18-0597fba831e1)

**Comment by mikan66** [comment]
See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/3d67c7bf95624ced7a4c8f12aeb5b75c2e29af29

closed with note move to "misc changes": https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/fa95275cf8ac938ab646ccef725d7e6cb1f8a2f6
