### ISSUE TITLE
Update portrayal of DistanceMark

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#35]
[Related portrayal sub-wg issue](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/39)

* _categoryOfDistanceMark_ was removed in FC 1.0.2 and _distanceMarkVisible_ was added.

* [ ] Update DistanceMark.lua based on portrayal sub-wg actions

**Comment by DavidGrant-NIWC** [comment]
Marked #65 as duplicate, see the issue for related comments

**Comment by mikan66** [comment]
Moved to #65 for easier tracking.
