### ISSUE TITLE
Update description of viewing group `22010` to include `DockArea`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#353]
`DockArea` is included in viewing group `22010` but is not currently included in the description.

Current: _Lake (LAKARE), sloping ground (SLOGRD), slope top (SLOTOP), dyke (DYKCON), causeway (CAUSWY), dam (DAMCON)_

Updated: _Lake, sloping ground, slope top, dyke, causeway, dam, dock area_

@alvarosanuy Please submit an update to the definition in the registry:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/6843a5f4-728c-41dd-8d3a-b60db58e9b86)

**Comment by alvarosanuy** [comment]
Gi registry does not allow me to enter any value for VGL field (which is mandatory). Consequently, I can't 'Submit' changes (Supersession) to existing VGs. GI Registry needs amendment by KHOA.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/70189016/3ecedec4-06a0-427f-8d7c-184efeaee29f)

**Comment by alvarosanuy** [comment]
Change proposal submitted on 05APR2024.
