### ISSUE TITLE
CardinalBuoy.lua typo

### ISSUE THREAD

**Issue by TDYCARHugh** [iho-ohi/S-101_Portrayal-Catalogue#354]
In CardinalBuoy.lua  at line 76 it looks like 'localOffsetX = -7.02' should have been 'textOffsetX = -7.02'

**Comment by DavidGrant-NIWC** [comment]
- [ ] Fix line 76
- [ ] Make textOffsetX a local instead of a global
  - [ ] also in IsolatedDangerBuoy.lua
