### ISSUE TITLE
BeaconLateral bug [PSWG #153]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#356]
See https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/153#issuecomment-2046554433

**Comment by DavidGrant-NIWC** [comment]
Checks such as `contains(11, feature.natureOfConstruction)` should be updated to `beaconShape == 4`. `natureOfConstruction` value `11` used to indicate lattice beacons, but is no longer permitted and instead `beaconShape` of `4` is used to indicate lattice beacons.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/30e1bf51-4a65-4026-a8ba-ce873bfb722c)

**Comment by mikan66** [comment]
See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/a337c869e28e73a7f57c28162724725bbc5b2502
