### ISSUE TITLE
Removal of IEC related symbols from S101 PC [PSWG #155]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#357]
Spec at https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/155#issuecomment-2048617927

**Comment by DavidGrant-NIWC** [comment]
Provided list of objects to be removed: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/155#issuecomment-2083400449

**Comment by DavidGrant-NIWC** [comment]
From https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/155#issuecomment-2221969397

> Decision at PsWG meeting on 10/7/2024
Retain all symbols until further notice. Close this issue.
