### ISSUE TITLE
Ice Area [PSWG #94]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#358]
SPEC https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/94#issuecomment-2048915950

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/e4821b1a-4597-47e5-85ad-9c5f968246d9)
