### ISSUE TITLE
Update Information - Portrayal of Deleted features [PSWG #152]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#359]
spec at https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/152#issuecomment-2050821356

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/c71f363e-7419-4b31-a955-8eac1964938c)
