### ISSUE TITLE
Geo feature Structure Over Navigable Water [PSWG #161, Row 2]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#360]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/68a739bb-65ab-4d87-88e2-602a8a9751ae)

**Comment by mikan66** [comment]
@alvarosanuy, placing "On Hold" awaiting symbology.

**Comment by DavidGrant-NIWC** [comment]
@alvarosanuy

* Does this participate in alerts?
  * Add to NavHazards?
  * ![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/7f1ccd8b-bab0-4d4a-9433-6844558badc5)

* Viewing group assignment?
  * Add to 12210 (part of the base display)?
  * ![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/70130b5a-374b-4f2f-89f6-43043f774311)

* Drawing priority?
  * 24 to match `SpanFixed` (although that doesn't have a fill)?

* OverRadar?

* Any labels?

I don't have a feature to test with, so here I modified the Dyke to portray as if it were a SONW:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/3dd953ce-b3c3-4e09-9ca7-6e9ddd8f9450)

**Comment by alvarosanuy** [comment]
> * Add to NavHazards?

**Agree**

> * Add to 12210 (part of the base display)?

**Agree**

> * Drawing priority?

**Agree**

> * OverRadar?

**Yes**


> * Any labels?

Nothing beyond **featureName** or clearances.

**Comment by DavidGrant-NIWC** [comment]
> Any labels?
Nothing beyond featureName or clearances.

Currently it doesn't show any clearance values. Do you want to show verticalClearanceFixed? I assume horizontalClearanceFixed would not be shown.

**Comment by alvarosanuy** [comment]
> Currently it doesn't show any clearance values. Do you want to show verticalClearanceFixed?

**Yes please.**

**Comment by DavidGrant-NIWC** [comment]
Implemented but not tested due to lack of test data.
