### ISSUE TITLE
Multiple QoBD & zone of confidence [PSWG #161, Row 15]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#362]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/e592b3aa-8b39-4f9e-8da6-8d1c3418d00a)

**Comment by DavidGrant-NIWC** [comment]
Noted as part of #314, will be handled as part of that issue.
