### ISSUE TITLE
“system” attribute in the water [PSWG #161, Row 21] 

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#365]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/ea97efee-fec6-4f69-bb03-bf857803df3c)

To do list:
- [x]  BuiltUpArea 
- [x] Building 
- [x] Landmark 
- [x] SiloTank 
- [x] WindTurbine 
- [x] FortifiedStructure 
- [x] Crane
- [x] Alerts & Indications mapping table  update

**Comment by mikan66** [comment]
@alvarosanuy, We need a viewing group for BASE when _in the water_ is True.

**Comment by alvarosanuy** [comment]
**This attribute applies to: **BuiltUpArea**, Building, Landmark, SiloTank, WindTurbine, FortifiedStructure and Crane.**
I would consider all these features but **BuiltUpArea**, as 'Infrastructure' that, when **inTheWater**=True, become 'Dangers above the water'.
I am of the opinion that **BuiltUpArea** 'in the water' should be considered as **ShorelineConstruction** though.

Accordingly, I recommend allocating:

-  **Building**, **Landmark**, **SiloTank**, **WindTurbine**, **FortifiedStructure** and **Crane** -- **Viewing Group 12210** (when the system attribute **inTheWater**=True).
- **BuiltUpArea** -- **Viewing Group 12410** (when the system attribute **inTheWater**=True).

Regarding 'Drawing Priority', I do not see the need to change their default value. 

**Alerts & Indications:**
- All the features but **BuilUpArea** (when 'In the water') will have to trigger an **indicationHighlight** and message.

- I think **BuiltUpArea** (when 'in the water') should be considered as **ShorelineConstruction** and therefore trigger **dangerHighlight**.

- Alerts & Indications mapping table must be updated accordingly, and a new version uploaded to [159](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/159)

**Comment by mikan66** [comment]
@alvarosanuy , here is a forced "inTheWater" sample of "BuiltUpArea", (obviously on land), but trying to get display correct. Also, for the boundary it will be LineInstruction:LOWACC21 always ON if "inTheWater".  Is this how you want it? 
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/de1e9cea-e9cd-436c-84e4-93b1bb46cc9e)

**Comment by alvarosanuy** [comment]
LOWACC21 is the correct symbology for the seaward boundary of a **BuiltUpArea** that sits on top of DEPARE. The area itself will have 50% transparency.
Note that it is possible for the **BuiltUpArea** to be encoded within an **Unsurveyed** area ..... At this point in time, I would follow the same encoding instructions for both scenarios with the only caveat that, if **BuiltUpArea** shares part of its boundary with the UNSARE limit, UNSARE wins over the display of the edge. Inside the UNSARE, portrayal will need more work to make it readable. This is a similar situation than the one we are facing with **IceArea** I'm afraid ........

Unfortunately, CARIS has not yet made available a version of their production tool that follows 1.2.3 and therefore we are unable to create Test data for you at this point in time ..... Maybe something Jonathan Pritchard can assist with.

**Comment by TDYCARHugh** [comment]
What features/attributes can be made with 1.2.3 that cannot be made with 1.2?  I don't see any functional difference between those feature catalogues. The main difference seems to be normalizing some of some associations.

**Comment by alvarosanuy** [comment]
@TDYCARHugh - We are using HPD 5.0.1. The system attribute is not visible in the GUI when editing or querying a **BuiltUpArea** that is created in the water. In theory, as a system attribute, once the feature is added over a depth area, the attribute should be auto-populated by the production tool as 'True' (and should be editable because is listed as not mandatory in DCEG). We can't see the attribute listed in the feature Tab; neither before creating the feature nor after the feature is created.
We run the cell in Analyzer (latest Beta version) and it reports an Error - **BuiltUpArea** not covered by Land. I wouldn't expect this message if the system attribute 'in the water' is encoded in the feature. We thought it may have been encoded by the production tool but, for some reason, we were just not able to 'see it'. The error message in Analyzer seems to disprove that theory ...
We'll upload screenshots tomorrow but **please, if we are not encoding the feature as we should**, let us know and we try again.
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/70189016/35d3fb8d-2744-4cc0-9e52-eb2cd5c24f62)
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/70189016/337148f9-3d98-44df-8671-0169440a4dd4)

**Comment by kusala9** [comment]
I can do a test dataset for testing, let me know what you need - @alvarosanuy if you email me what you need I'll see what I can do this week.

**Comment by alvarosanuy** [comment]
@kusala9 - We need a **BuiltUpArea** captured:

1.  On land but extending offshore and having half of the feature sitting on **DepthArea**. The **BuiltUpArea** must have the system attribute 'In the water'=True. I imagine that the feature will have to be split in two as the attribute 'In the water' wouldn't make sense with the half that sits on Land ... (maybe something to clarify in the DCEG  - @JeffWootton).
2. Same than above but with a part on Land and the rest overlapping **UnsurveyedArea**.
3. You could also do a couple of **BuiltUpArea** 'Islands', one sitting completely over **DepthArea** and the other one fully inside an **UnsurveyedArea**.

Please make sure that the **DepthArea** overlapping **BuiltUpArea** contains some soundings, obstructions and depth contours to help with the testing of Transparency.

Thanks!!

**Comment by JeffWootton** [comment]
@alvarosanuy: `I imagine that the feature will have to be split in two as the attribute 'In the water' wouldn't make sense with the half that sits on Land ... (maybe something to clarify in the DCEG)`

No, the intention is not to have the Built-Up Area split a the coastline. The inTheWater attribute is a "system" attribute used to contribute to setting the display priority in the ECDIS only (to be included in Base display as the feature extends over the water), and is included in the list of attributes that are to be suppressed in the ECDIS Pick Report.

I have included some additional guidance on this in the DCEG.

**Comment by TDYCARHugh** [comment]
CARIS customer support team can assist with getting set up to make test S-101 1.2.3 data with HPD 5.0.2.

**Comment by kusala9** [comment]
[cell.zip](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/files/15081140/cell.zip)

try this. Test cell with (I think) the features you want. Let me know if you need any others. inTheWater has been set. This is on v1.3.0 and the zip has a 5.1.0 FC in it so you can load it in the current viewer....

**Comment by alvarosanuy** [comment]
@mikan66  - Can you please upload screenshots? Thanks

> try this. Test cell with (I think) the features you want. Let me know if you need any others. inTheWater has been set. This is on v1.3.0 and the zip has a 5.1.0 FC in it so you can load it in the current viewer....

**Comment by mikan66** [comment]
DCEG 1.3 No requirement to split built-up area at coastline boundary into "in the water" true/false parts
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/9680b978-8a53-445b-8f87-933b0586b842)

**Comment by mikan66** [comment]
See some prior work regarding this topic at #256.   All appear to need alerts review or addition of alerts processing.

**Comment by mikan66** [comment]
Needs testing, see commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/351371741da6cf07a6f20ed592108fc9569e0b62
