### ISSUE TITLE
Corrected `verticalClearanceOpen` on `Gate` [PSWG #161, Row 28]  

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#366]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/5fd6eaff-b94e-47ab-834f-acbf3b3c5e06)

**Comment by DavidGrant-NIWC** [comment]
@alvarosanuy

`Gate` doesn't currently display the clearance value because S-52 didn't. Please confirm that you want to add this to the portrayal.

**Comment by alvarosanuy** [comment]
Please add the portrayal of Clearances to **Gate**.

**Comment by DavidGrant-NIWC** [comment]
@alvarosanuy is there a chance of confusion between the horizontal and vertical clearance values? The portrayal has been updated to show the vertical clearance open ("clr op x"), but the horizontal clearance is not displayed.

**Comment by alvarosanuy** [comment]
The DCEG change is about Vertical Clearance, there's nothing new for Horizontal **but**, I guess, labelling one and not the other does not make a lot of sense. I believe we should follow what we do for **Bridges** and label all **Gates** clearances the same way. Both Clearances are important.

**Comment by DavidGrant-NIWC** [comment]
@alvarosanuy
1. Recommend remove "op" since there is no need to distinguish from clearance closed.
1. How to distinguish the vertical from horizontal?
    * "clr x" and "| clr x |"?
    * Shown here on two spans since I don't have a Gate with the proper attribute values:
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/765febc4-661a-4b12-9b93-d548cee0c0b0)

**Comment by alvarosanuy** [comment]
Sorry for the confusion. In my mind I thought there was a way to depict Horizontal Clearances in S-52/S-101 but that's not the case.
I think we need to come up with a way of portraying this info as it is very important for Bridges as well.
Personally, I think the easiest way is to precede the current text strings with 'H-' or 'V-' (e.g. H-clr op 15). Having said this, this would be new portrayal and I need it to run it by the PsWG.

- [ ] **NIWC** - Please Update the Rule for **Gate** to show text string for Vertical Clearance only. Recommend retaining 'op' for consistency with the name of the feature attribute.
- [ ] **Alvaro** - Create a new Portrayal GitHub issue to discuss depiction of Horizontal Clearances.
