### ISSUE TITLE
AreaFill `PRTSUR01` is unreferenced

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#372]
@JeffWooton and/or @alvarosanuy, does this apply in S-101? Is it valid to encode unknown for `depthRangeMinimumValue` and `depthRangeMaximumValue`?

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/2310c8d5-2775-44f6-8810-593b212a0d8c)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/a71a66a0-39de-4294-90ac-f119f147b898)

**Comment by alvarosanuy** [comment]
I think that it is technically possible because DRVAL1 and DRVAL2 are mandatory attributes for DEPARE and, when their values are not known, the attribute must be populated with an empty (null) value (DCEG 2.4.4).

In Australia, we do not have any instances of that type of encoding in our ENCs but, according to the definition for AP(PRTSUR01) in S-52 PL 4.0.3 Part I Addendum, the encoding will trigger an area portrayal that indicates an 'Incompletely Surveyed Area'.
This portrayal is very close to the UNSARE one, the only difference I believe is the spacing between the dashes.
[Extracts from S-52 PL.docx](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/files/15156965/Extracts.from.S-52.PL.docx)

**Comment by DavidGrant-NIWC** [comment]
@alvarosanuy @jeffwootton
In S-52 a depth area with unknown min/max depth will bypass CSP(DEPARE03) which means it's not part of the safety contour and won't generate alerts. Unless directed otherwise, the S-101 implementation will also behave this way.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/4af132f6-4ff7-4137-8438-74570d9a968f)

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/5e3cfd44-271d-4e0b-aa5b-2af907804298)

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC  - Agree on mirroring S-52 for now BUT,
**Question**: Shouldn't CSP(DEPARE03) do something about DRVAL1=Unknown. I think there are merits to treat it as zero! I would like to see this type of DEPARE encoding triggering the Safety Contour Alarm!
On the same premise, the Shallow Water Pattern should cover the area.

Beyond that I would like to hear from @JeffWootton regarding the intent (use cases) for this type of encoding and maybe challenge the need for it in S-101. If permitted, it has to trigger A&I. An 'Incompletely Surveyed Area' seems closer to UNSARE than DEPARE ...

It would be interesting to know if any country has published an ENC with that encoding.
@MikusRL - Can you do a global search on DEPARE having DRVAL1=Unknown and DRVAL2=Unknown?

@TomRichardson6

**Comment by JeffWootton** [comment]
@alvarosanuy: Beyond that I would like to hear from @JeffWootton regarding the intent (use cases) for this type of encoding and maybe challenge the need for it in S-101:

I cannot think of a circumstance where the `depthRangeMinimum` value on a `DepthArea` would be populated as "unknown" unless a relationship has not been established between the sounding and height datums in which case the `depthRangeMinimum` for a drying area could be unknown (but I am not aware of this scenario occurring anywhere).

I am aware of `depthRangeMaximum` being populated for the deepest depth area(s) in a dataset where the depth measurement equipment has been incapable of reaching the seabed, but again this is rare from my experience - even where an area is swept to a defined depth there is generally underlying spot survey data from which `depthRangeMaximum` can be derived.

In S-57 (and I would assume also in S-101) validation there is a Validation Check (in S-58 Check 509) that checks that values have been populated for these attributes (stating that the feature is meaningless without these values); and categorized as Error (and also noting that DCEG clause 2.4.4 is very generic).

**Comment by MikusRL** [comment]
> It would be interesting to know if any country has published an ENC with that encoding.
> @MikusRL - Can you do a global search on DEPARE having DRVAL1=Unknown and DRVAL2=Unknown?

@alvarosanuy 
Checked the PRIMAR DB and from there the global result is as follows:
- total DEPARE encoded
3742390 features from 20865 cells from 79 producers
- DEPARE having DRVAL1=Unknown:
124192 features from 1941 cells from 11 producers.
- DEPARE having DRVAL2=Unknown:
500 features from 202 cells from 8 producers.
- DEPARE having DRVAL1=Unknown and DRVAL2=Unknown
6 features from 2 cells from 1 producer.

Use cases that I randomly picked across reported producers when DRVAL1 is unknown:
- encoded as inter-tidal (most of the cases)
- encoded together with just the M_QUAL with CATZOC=U (just a few)

Use cases in the same way picked for DRVAL2 is unknown:
- encoded together with the SWPARE (a lot of cases)
- encoded together with just the M_QUAL with CATZOC=U to CATZOC=A1 (also a lot of cases). Sometimes also as depth areas with no contour lines around those. 

Use cases for DRVAL1 and DRVAL2 is unknown:
- encoded together with just the M_QUAL CATZOC=U
- encoded together with OBSTRN with CATOBS=6 (foul area) + M_QUAL CATZOC=U
- encoded together with FSHFAC with CATFIF=2 (fish trap) + M_QUAL CATZOC=U

Hope this helps.

**Comment by DavidGrant-NIWC** [comment]
Note that if `depthRangeMinimum` is unknown but `depthRangeMaximum` has a value then CSP(DEPARE03) is called. The CSP treats the minimum depth as if it was -1 and the feature will receive an alert assignment and show the shallow pattern overlay.

It's only when both min and max are unknown that this odd behavior occurs.
