### ISSUE TITLE
Update version from 1.3.0-PR to final release 1.3.0 after peer review

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#388]
Update version from 1.3.0-PR to final release 1.3.0 after peer review period.

**Comment by alvarosanuy** [comment]
I think we should proceed with this activity and close this issue. Jeff may want to upload 1.3.0 to the testBed section of the GI registry.

**Comment by mikan66** [comment]
@JeffWootton, @alvarosanuy Based on UpdateInformation meeting today about published versions, I think further guidance on the way forward here with versioning is needed.  I can baseline "1.3.0-PR" to "1.3.0", but then what's next? 1.3.1 or 1.4.0, etc....please advise.

**Comment by JeffWootton** [comment]
@mikan66 If there is a requirement for another interim version before 2.0.0 (I hope not!) it will be 1.4.0, noting that 1.3.0 and any other version before 2.0.0 will be an "unofficial" draft for essentially S-101PT Members only.

**Comment by mikan66** [comment]
See Github release https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/9ead5a6e7e13f37b64c0713700892aacd711133f
