### ISSUE TITLE
Update portrayal of `DistanceMark` [PSWG 162] [DCEG GAP 1.3.0_2.0.0 Row 9]

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#392]
Update portrayal of `DistanceMark` once https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/162 is finalized.

**Comment by mikan66** [comment]
Related [DCEG GAP 1.3.0_2.0.0 Row 9]
