### ISSUE TITLE
Update alignment of `TextPlacement` per S-101PT13-07.8

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#396]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/893f5bf7-241a-4bfe-99f6-e64f3773148a)

**Comment by DavidGrant-NIWC** [comment]
@TDYCARHugh 

What should the alignment be when the offset is zero (bearing in mind that there is no requirement that the position of the placement feature matches the position of the associated feature)? I'm thinking center/center because zero offset is most likely to be used when `TextPlacement` is associated to a feature with surface geometry.

**Comment by TDYCARHugh** [comment]
I don't think a 0 offset has been considered.  I guess we can decide as you say, that a 0 offset means to centre the text and if you want to have the auto placement kick in then you can apply at least a very small offset.
