### ISSUE TITLE
Added `UpdateAggregation` [DCEG GAP 1.3.0_2.0.0 Row 41]

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#406]
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/62906211/7cbf5f79-7126-456d-b8ed-6dbebf356db3)

**Comment by alvarosanuy** [comment]
**Hi Dave, sadly we do not have a version of CARIS to produce S-101 products to Ed 1.3.0 at this point in time. we hope this changes by the end of the week, but we won't be able to give you any test data until next week.
As far as you can implement something based on the theory below, we could then fine tune all that for PC 1.5.0**

![image](https://github.com/user-attachments/assets/cd7fe1b5-e3e6-4aa3-8338-667ae1714bf6)

The 2 main use cases described in the DCEG are:
![image](https://github.com/user-attachments/assets/0f143717-392d-4d9c-afad-5668bbc376ee)

**Comment by DavidGrant-NIWC** [comment]
Understood - we'll try to move forward with what we have. I just started looking into this this evening; I'm not sure that any portrayal changes will be needed since the aggregation(s) don't affect the portrayal of the individual `UpdateInformation` features. I'll look at it some more tomorrow.

I do think the DCEG guidance may need a little updating:
* I believe when a move is portrayed the encoding of the curve connecting the new and old location should be optional (at the discretion of the encoder).
* I think I understand what the highlighted entry is getting at, but I still find it confusing. It makes it seem like the container of an `UpdateAggregation` has to have `updateType`=`modify`. However, the container can alternatively have `updateType`=`move`. Clause 25.20 has a better description.
![image](https://github.com/user-attachments/assets/b601ce3a-bf31-481a-a4a5-406d12373406)

**Comment by alvarosanuy** [comment]
> I'm not sure that any portrayal changes will be needed since the aggregation(s) don't affect the portrayal of the individual `UpdateInformation` features.

**I tend to agree**; my understanding is that it would help with the presentation of overall update action to the mariner in ECDIS [e.g. a layered approach, where a "move' is identified as the top-level update action, and their constituents (delete & insert) would be listed below and simultaneously highlighted when the top-level layer is selected by the user].

**Comment by DavidGrant-NIWC** [comment]
No changes are required but error checking will be added to ensure when the geometry type is `None` the `updateType` is either `modify` or `move`.
