### ISSUE TITLE
Mooring Trot (row 16 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#42]
20220422_S101 Portrayal_Consolidation of pending actions.xlsx

Update MooringTrot to display featureName.name.

Dave: can we just add something like this to the aggregated feature (has no geometry)?
		if feature.featureName[1] and feature.featureName[1].name then
			featurePortrayal:AddInstructions('LocalOffset:-3.51,3.51;TextAlignHorizontal:End;FontSize:10')
			featurePortrayal:AddTextInstruction(EncodeString(GetFeatureName(feature, contextParameters), 'by %s'), 21, 24, 21010, 24)

**Comment by DavidGrant-NIWC** [comment]
> Dave: can we just add something like this to the aggregated feature (has no geometry)? if feature.featureName[1] and feature.featureName[1].name then featurePortrayal:AddInstructions('LocalOffset:-3.51,3.51;TextAlignHorizontal:End;FontSize:10') featurePortrayal:AddTextInstruction(EncodeString(GetFeatureName(feature, contextParameters), 'by %s'), 21, 24, 21010, 24)

TextInstruction is relative to the features geometry, so it wouldn't know where to display the text.
