### ISSUE TITLE
Update catalog version to 1.4.0 prior to release

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#421]
Update catalog version from "1.4.0-DRAFT" to "1.4.1" prior to release.

**Comment by DavidGrant-NIWC** [comment]
The PC version should be 1.4.0; the FC will be 1.4.1

**Comment by mikan66** [comment]
Incorrect, as directed by Tom R 7/18/24: "PC 1.4.1 though to be consistent with the DPS and DCEG"

**Comment by DavidGrant-NIWC** [comment]
@TomRichardson6

It's misleading to implementers to keep trying to align the third digit. There is no 1.4.0 PC; why are we releasing as 1.4.1?

**Comment by TomRichardson6** [comment]
@DavidGrant-NIWC and @mikan66 

I guess that I was presuming that 1.4.0 has been generated but if it has not then please provide 1.4.0 next week and we will just be clear that 1.4.0 targets FC 1.4.1.

**Comment by mikan66** [comment]
Update catalog version from "1.4.0-DRAFT" to "1.4.0" prior to release.
