### ISSUE TITLE
Clearance label on `Gate` can overwrite curve

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#432]
![image](https://github.com/user-attachments/assets/3d277106-a0c0-4fa8-8763-efb99b16ea9b)

When geometry is curve, use local offset of 3.51,-3.51 and align to start rather than center (to limit overwriting of vertical lines).

**Comment by mikan66** [comment]
![image](https://github.com/user-attachments/assets/e20459fb-686a-4fa7-8971-4990646058e4)
