### ISSUE TITLE
`MooringArea` in wrong display plane

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#433]
Point geometry is being assigned to `OverRadar` when radar is off.
![image](https://github.com/user-attachments/assets/5c6e4016-de83-4486-996e-de51b4bbece6)

**Comment by mikan66** [comment]
![image](https://github.com/user-attachments/assets/3367d343-fa3a-47fd-a49f-2b848a7aa81d)
