### ISSUE TITLE
Should "(man)" label on `FogSignal` be using text group `23 - Light Description`?

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#434]
The "(man)" label on `FogSignal` features is output using text group `23`. Text group `23` is named "Light Description". Should this be using a different text group?

![image](https://github.com/user-attachments/assets/989ac00a-2ffb-402f-b81a-83f48d52d3c8)

**Comment by alvarosanuy** [comment]
> Should this be using a different text group?

Personally, I am not a fan of creating millions of selectors for mariners.... They do provide flexibility but, I believe, they also add complexity and confusion when handing the watch over. The 'next person' needs to understand what's On and what's Off ...
**I would prefer renaming IVG23** to 'Text: Light **& Fog Signal Description**' than creating a brand new IVG for 'Fog Signal Description'.

**Comment by DavidGrant-NIWC** [comment]
> Personally, I am not a fan of creating millions of selectors for mariners.... They do provide flexibility but, I believe, they also add complexity and confusion when handing the watch over. The 'next person' needs to understand what's On and what's Off ... 

I agree; I should have been clearer. I wondered if one of the other existing entries is more appropriate, specifically `24 - Supplementary Information`.

> **I would prefer renaming IVG23** to 'Text: Light **& Fog Signal Description**' than creating a brand new IVG for 'Fog Signal Description'.

@TomRichardson6 do you have a preference?

**Comment by TomRichardson6** [comment]
To me supplementary information would seem quite appropriate. I fully agree that creating an additional one just for this should be avoided. 

However, renaming 23 to Aids to Navigation Description could be a means to future proof S-101 and also potentially cover Radar and other aids that are neither lights nor fog signals. @alvarosanuy what do you think to this variance on your suggestion?

**Comment by alvarosanuy** [comment]
Happy with @TomRichardson6 proposal but maybe call it 'Aids to Navigation **Information**' instead of Description?

**Comment by TomRichardson6** [comment]
@alvarosanuy I am happy with that approach.

**Comment by DavidGrant-NIWC** [comment]
Closing: will continue using viewing group 23. Viewing group 23 will be renamed via #439
