### ISSUE TITLE
multiplicity of attribute category of dolphin 

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#437]
Amend multiplicity of attribute category of dolphin on feature Dolphin from [1..1] to [1..*].

Ref: https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/171
![image](https://github.com/user-attachments/assets/9d064fad-1623-4c6c-a561-fbf68e9c777e)

Reference FC attribute entries for multiplicity upper infinite="true" />

if feature.categoryOfDolphin and #feature.categoryOfDolphin  then
      for _, COD in ipairs(feature.categoryOfDolphin) do
       -- check COD for value 2 and assign MORFAC04 else MORFAC03

**Comment by mikan66** [comment]
![image](https://github.com/user-attachments/assets/d0d988c3-2a0f-4619-ae9b-92de1f2b85f7)

**Comment by DavidGrant-NIWC** [comment]
Should only draw a single symbol. If group agrees with this comment, then modify as indicated:
https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/171#issuecomment-2324372602

**Comment by alvarosanuy** [comment]
Agree to show' Deviation Dolphin' symbol ONLY every time **categoryOfDolphin** includes the value (2). The other symbol will be used in all other instances.

**Comment by mikan66** [comment]
![image](https://github.com/user-attachments/assets/113c972e-dc4c-41ee-b8f2-0854fc53fff5)
