### ISSUE TITLE
`DepthContour` not portrayed

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#456]
`DepthContour` may not be portrayed when it is assumed to coincide with the safety contour. The logic implementing this is incorrect and can result in the `DepthContour` not being visible in some ECDIS configurations. For instance, using the dataset available here: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/455#issuecomment-2477062671

|MSSC|Result|
|:---:|:---:|
|6|![image](https://github.com/user-attachments/assets/d560348e-64af-433f-8ba7-8ab425cc8e09)
|0|![image](https://github.com/user-attachments/assets/5fecacbb-7df7-4ac8-8251-aab59d695cc1)

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/user-attachments/assets/291b94a6-db6f-41ef-8ea2-c2b9c51c5eeb)

**Comment by alvarosanuy** [comment]
**PsWG meeting on 03/12/24**

It was decided to resolve this shortfall in PC 2.0.0. For this, the SWG was advised that a change proposal to PC 2.0.0 has to be submitted via a MS as part of the consultation process under IHO CL39/2004.

- [ ] **Australia** submit a change proposal before the closing date (13/12/24).
