### ISSUE TITLE
Symbols still include inline styling

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#457]
The "svg" element still contains inline styling:

![image](https://github.com/user-attachments/assets/2e7588a9-201c-44d5-957f-caf8c9134f89)

Should instead use attributes "shape-rendering" and "fill-rule" rather than setting these via properties. See _S-100 Table 9-B-4 – Style properties_

**Comment by mikan66** [comment]
718 SVG file will be updated to replace above with: 
![image](https://github.com/user-attachments/assets/482c23dc-9621-4315-ac40-01d6557f0752)

**Comment by DavidGrant-NIWC** [comment]
NOTE: Although we validate the entire contents of the PC prior to each release, the reason this wasn't caught when applying #177 is because the S-100 5.2 SVG schema currently allows inline styling ("for backwards compatibility"). This seems odd/inconsistent; the older schemas provide backwards compatibility.

Recommend that this is corrected in the next update to S-100. @rmalyankar is there an active GitHub repo to report schema issues?

**Comment by rmalyankar** [comment]
The schema includes the style attribute but says it is deprecated. S-100 9-B-4.2 says "Robust parsers and renderers may interpret the content of the style attribute.".
This should be submitted as a maintenance proposal for Edition 6.0.0.

**Comment by DavidGrant-NIWC** [comment]
The problem is that symbols which are not valid per S-100 5.2 are not detected during validation (the issue noted above). At minimum there should a check to ensure these symbols are flagged. There is no guarantee the implementing application will have a robust parser or renderer.
![image](https://github.com/user-attachments/assets/ffaa2785-87bc-41e3-a26e-eef39c8f8b8a)

**Comment by rmalyankar** [comment]
The _style_ attribute was included in the original of the 5.2 schema prepared by Holger, with a comment saying it is deprecated. The 5.2 SVG schema has been through all the review/approval stages - WG, HSSC, MS.  I do not think there will be much objection to removing it in Edition 6.0.0 but it still needs to go through the process.
