### ISSUE TITLE
NavigationalSystemOfMarks (row 17 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#47]
Reference: 20220422_S101 Portrayal_Consolidation of pending actions.xlsx

see new symbol: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/64

**Comment by mikan66** [comment]
Already incorporated as part of Local Direction of Buoyage (row 14 main) #46

**Comment by mikan66** [comment]
action to change portrayal of NavigationalSystemOfMarks to NullInstruction

**Comment by mikan66** [comment]
https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/9df779db6fcfe88025d1b943d404f8ada6a7316e

**Comment by mikan66** [comment]
See https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/42#issuecomment-1226701046.
Remove Plainboundaries check in NavigationalSystemofMarks.lua

Alvaro - should this be the same for LocalDirectionOfBuoyage.lua as well? (#64 PSWG)

**Comment by alvarosanuy** [comment]
**NavigationalSystemOfMarks** must not symbolise its surface boundaries; this is irrespective of the value of **marksNavigationalSystemOf**. Mariners will know the system in force by referring to the ECDIS legend on the screen.

For **LocalDirectionOfBuoyage**, we will show surface boundaries as per S-52 M_NSYS [LC(NAVARE51) or (DASH,1)] unless **marksNavigationalSystemOf** & **orientationValue** values are _Unknown_, when neither a surface boundary nor a central symbol should be displayed.
For central symbols when **orientationValue** is populated, refer to PSWG [Issue # 64](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/64) - Final decision made by the S101PsWG on 15/7/22.

**Comment by mikan66** [comment]
See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/9b603dd5221f2150dc7ab18703ddb07672ccb86b
