### ISSUE TITLE
Quality of Bathymetric Data (Row 21 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#50]
Reference: 20220422_S101 Portrayal_Consolidation of pending actions.xlsx

Rule Update Note: Sanchez, Alvaro MR:
Decision has been made to use S-52 symbology based on CATZOC value.

Surface only primitive.
![image](https://user-images.githubusercontent.com/4913543/166930288-753f2185-6dca-41aa-b281-d99f158a4703.png)

S-52 PresLib Ed 4.0.3 Part I App B Look-up Table Areas Plain Boundaries.docx
![image](https://user-images.githubusercontent.com/4913543/166929460-b99a28bc-0a0b-4418-b47d-ed026d3bfc27.png)

S-52 PresLib Ed 4.0.3 Part I App C Look-up Table Areas Symbolized Boundaries.docx
![image](https://user-images.githubusercontent.com/4913543/166929978-af454386-684e-4b8c-86a5-fb51be181388.png)

**Comment by DavidGrant-NIWC** [comment]
`CATZOC` should have priority 12 in S-101 (priority is 4 in S-52)

![image](https://user-images.githubusercontent.com/62906211/230222735-86c616e0-ccc3-4173-a848-a6114efcd19f.png)

**Comment by TDYCARHugh** [comment]
Agree priority should be 12.
