### ISSUE TITLE
Flare Stack (row 52 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#63]
![image](https://user-images.githubusercontent.com/4913543/167470944-bb7187fd-7d55-484c-889c-3b25341d3b87.png)

Need more info.

**Comment by alvarosanuy** [comment]
OFFICIAL
Hi Mikan,

The instruction in the latest version of ‘Jeff’s spreadsheet’ is to display the international abbreviation 'Fla' next to symbol as per INT1 L11

I would use the same font than the one currently used to display CATLIT=1 (directional function) abbreviation ‘Dir’.

Alvaro

Alvaro Sanchez | Acting Director National Charting
Australian Hydrographic Office | Maritime Geospatial Branch
8 Station Street, Wollongong
T: +61 2 4223 6506 | M: +61 434 349 674

Defence Intelligence Group | Department of Defence
[AGO Logo2]

IMPORTANT: This email remains the property of the Department of Defence. Unauthorised communication and dealing with the information in the email may be a serious criminal offence. If you have received this email in error, you are requested to contact the sender and delete the email immediately.


From: mikan66 ***@***.***>
Sent: Tuesday, 10 May 2022 4:10 AM
To: iho-ohi/S-101_Portrayal-Catalogue ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [iho-ohi/S-101_Portrayal-Catalogue] Flare Stack (row 52 main) (Issue #63)


 ⚠  EXTERNAL EMAIL: Do not click any links or open any attachments unless you trust the sender and know the content is safe.  ⚠.

[image]<https://user-images.githubusercontent.com/4913543/167470944-bb7187fd-7d55-484c-889c-3b25341d3b87.png>

Need more info.

**Comment by mikan66** [comment]
'Fla' text added to point and surface for OffshorePlatform.lua with Flare Stack.
See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/e994bd486011b5e1c3fcec80808c0f39b97fe757
