### ISSUE TITLE
High Speed Ferry [Category of Ferry] (row 54 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#64]
![image](https://user-images.githubusercontent.com/4913543/167471144-a0f2258b-5f2a-43d7-9c62-ab9a33d98e2e.png)

Need more info for FerryRoute.lua, for value: 5 - High Speed Ferry.  Furthermore, 3 - Ice Ferry not addressed either.

**Comment by alvarosanuy** [comment]
OFFICIAL
Hi Mikan,

I retrieved the original input for this entry in the final version of ‘Jeff’s spreadsheet’. See below:

recommend amending the rule to give categoryOfFerry 5 (High Speed Ferry) the same symbology than categoryOfFerry 1 (Free Moving Ferry).

In S-52, 3 - Ice ferry, does not have its own symbology and it displays using the ‘default’ symbology, which in fact is the one used by 2 -cable ferry. This means using LC(FERYRT02) for lines or SY(FRYARE52) for areas.
I would use the same symbology in S-101. No need to come up with a different symbology.

Hope it helps,

Alvaro

Alvaro Sanchez | Acting Director National Charting
Australian Hydrographic Office | Maritime Geospatial Branch
8 Station Street, Wollongong
T: +61 2 4223 6506 | M: +61 434 349 674

Defence Intelligence Group | Department of Defence
[AGO Logo2]

IMPORTANT: This email remains the property of the Department of Defence. Unauthorised communication and dealing with the information in the email may be a serious criminal offence. If you have received this email in error, you are requested to contact the sender and delete the email immediately.


From: mikan66 ***@***.***>
Sent: Tuesday, 10 May 2022 4:14 AM
To: iho-ohi/S-101_Portrayal-Catalogue ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [iho-ohi/S-101_Portrayal-Catalogue] High Speed Ferry [Category of Ferry] (row 54 main) (Issue #64)


 ⚠  EXTERNAL EMAIL: Do not click any links or open any attachments unless you trust the sender and know the content is safe.  ⚠.

[image]<https://user-images.githubusercontent.com/4913543/167471144-a0f2258b-5f2a-43d7-9c62-ab9a33d98e2e.png>

Need more info for FerryRoute.lua, for value: 5 - High Speed Ferry. Furthermore, 3 - Ice Ferry not addressed either.

**Comment by mikan66** [comment]
categoryOfFerry 5 (High Speed Ferry) added to rule FerryRoute.lua

See commit [3d2d1d5](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/3d2d1d580cdda9f46fd44d4be72e1ecbf6952ca3)
