### ISSUE TITLE
Quality of Bathymetric Data (Date Dependent Processing)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#66]
In addition from DCEG 1.0.2 [NOTE: The modelling of the complex attributre zone of confidence and accompanying encoding guidance in this Edition of S-101 Annex A is intended to allow for 2 options for the encoding of degrading bathymetric data quality over time for testing purposes. One of the options described must be used when encoding the quality of bathymetric data for an area. This modelling will be consolidated when the preferred option has been determined. See also clause 24.5.]

NIWC Recommends: to use survey date range.

Also, See issue #50.

**Comment by DavidGrant-NIWC** [comment]
Remove test label since this is a duplicate of #80
