### ISSUE TITLE
Obstruction (row 18 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#72]
Sanchez, Alvaro MR:
Obstruction and OBSTRN07 rules have to be updated so that this feature is assigned to display category "Base" if the danger posed by the feature cannot be determined due to missing attributes, and is only assigned to display category "Other" if supporting attributes are present.

FINAL.Actions_28JUL2021.1.xlsx (row 22) 

 - S-101 portrayal rules do not implement S-52 CSP DEPVAL02 because the DEPVAL02 output "LEAST_DEPTH" and "SEABED_DEPTH" are provided via attributes on the relevant features (Wreck / Obstruction / UnderwaterAwashRock). 
 - While testing using the S-164 data we see a Wreck assigned to display category "Other" which should have been assigned to "Base". The issue is that the attributes "valueOfSounding", "expositionOfSounding" and "surroundingDepth" are missing / null. 

Also covers UnderwaterAwashRock (row 32 main)
Also see related issue #58 

- [ ] Obstruction
- [ ] UnderwaterAwashRock
- [ ] FoulGround (OBSTRN with CATOBS=7)

**Comment by DavidGrant-NIWC** [comment]
Related: #48
