### ISSUE TITLE
Value of Local Magnetic Anomaly (row 100 main) [PSWG #102]

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#73]
Sanchez, Alvaro MR:
Display text string using magneticAnomalyValueMaximum

FINAL.Actions_28JUL2021.1.xlsx (row 127)

![image](https://user-images.githubusercontent.com/4913543/170316104-6d62f9ca-ef34-4bb4-8350-31ff100d9cc6.png)

**Comment by mikan66** [comment]
From DCEG 1.0.2: The deviation is assumed to be positive and negative. The plus/minus character must not be encoded.
![image](https://user-images.githubusercontent.com/4913543/171219214-b0e7ceb0-81fa-4b54-b79c-0c45f71fe026.png)

**Comment by IngaFjellanger** [comment]
From  DCEG 4.2.1:
_... Where the positive and negative values for the **local magnetic anomaly** differ, the positive value must be populated in **anomaly value maximum**, and the negative value in the sub-attribute **magnetic anomaly value minimum**..._

What will happen if the absolute (numerical) value of **magnetic anomaly value minimum** is larger than the absolute (numerical) value of **magnetic anomaly value maximum** ? It is the **magnetic anomaly value maximum** which will be displayed.

**Comment by alvarosanuy** [comment]
> From DCEG 4.2.1: _... Where the positive and negative values for the **local magnetic anomaly** differ, the positive value must be populated in **anomaly value maximum**, and the negative value in the sub-attribute **magnetic anomaly value minimum**..._
> 
> What will happen if the absolute (numerical) value of **magnetic anomaly value minimum** is larger than the absolute (numerical) value of **magnetic anomaly value maximum** ? It is the **magnetic anomaly value maximum** which will be displayed.

Refer to DCEG guidance in section 4.2.
Maybe a better implementation is to:

- When **magneticAnomalyValueMinimum** is not populated or Unknown:
depict the value of **magneticAnomalyValueMaximum** preceded by '**±**'.
    For example **±4°**
- When both, **magneticAnomalyValueMaximum** and **magneticAnomalyValueMinimum** are populated with a value different to Unknown:
in brackets, depict '**+**' followed by **magneticAnomalyValueMaximum**, followedd by '**/**', followed by '**-**', followed by **magneticAnomalyValueMinimum**.
     For example **(+4°/-6°)**

**Comment by KlasOstergren-SMA** [comment]
> Refer to DCEG guidance in section 4.2. Maybe a better implementation is to:
> 
> * When **magneticAnomalyValueMinimum** is not populated or Unknown:
>   depict the value of **magneticAnomalyValueMaximum** preceded by '**±**'.
>   For example **±4°**
> * When both, **magneticAnomalyValueMaximum** and **magneticAnomalyValueMinimum** are populated with a value different to Unknown:
>   in brackets, depict '**+**' followed by **magneticAnomalyValueMaximum**, followedd by '**/**', followed by '**-**', followed by **magneticAnomalyValueMinimum**.
>   For example **(+4°/-6°)**

S-4 (B-274.1) states:
"Where the magnetic compass is known to be deflected either to the west alone or to the east alone, 5°W or 5°E should be quoted, rather than +5° or -5°, to reduce the ambiguity resulting form either a W or E 'normal' variation in the general area. Where the deflection may be in either direction it is expressed as ±5°."

Do we think this is applicable in this case?

**Comment by alvarosanuy** [comment]
Good point.

My understanding is that, by definition, East declination is a positive(+) number and West declination is a negative(-) number.
DCEG instructs to encode Positive values in **magneticAnomalyValueMaximum**

Therefore the portrayal instructions should be:

- When **magneticAnomalyValueMinimum** is not populated or Unknown:
depict the value of **magneticAnomalyValueMaximum** preceded by '**±**'.
    For example **±4°**
- When both, **magneticAnomalyValueMaximum** and **magneticAnomalyValueMinimum** are populated with a value different to Unknown:
in brackets, depict '**magneticAnomalyValueMaximum**' followed by '**E**', followedd by '**/**', followed by '**magneticAnomalyValueMinimum**', followed by '**W**'.
     For example **(4°E/6°W)**

**Comment by MikusRL** [comment]
From Klas comment above and earlier experience I propose to further fine-tune the possible combinations. This might be an "overkill", but at least this would then be unambiguous for encoders and consistent in implementation, and might help in future for ENC printing to paper as backup:

-  When both, magneticAnomalyValueMaximum and magneticAnomalyValueMinimum are populated with the same value and with a value different to Unknown:
depict the value of magneticAnomalyValueMaximum preceded by '±'.
For example ±4°

- When both, magneticAnomalyValueMaximum and magneticAnomalyValueMinimum are populated with different values and with a value different to Unknown:
in brackets, depict 'magneticAnomalyValueMaximum' followed by 'E', followed by '/', followed by 'magneticAnomalyValueMinimum', followed by 'W'.
For example (4°E/6°W)

- When either one, magneticAnomalyValueMaximum or magneticAnomalyValueMinimum is populated with a value and the other respective subattribute is not populated:
in brackets, depict populated subattributes value followed by 'E', if the populated value is 'magneticAnomalyValueMaximum' or 'W', if the populated value is 'magneticAnomalyValueMinimum'.
For example (4°E) or (6°W)

- When magneticAnomalyValueMaximum is populated with Unknown and magneticAnomalyValueMinimum is not populated or Unknown:
portray only the border of the anomaly's geometry;
or,
depict text "Magnetic Anomaly".
For example Magnetic Anomaly

The third option would cover the instances, mentioned by Klas (therefore proposed also changes to first and second), and the fourth would cover the instances, where the data is either very old and might be considered not portray exact values, or where there is no specific value reported or specific values do not exist in the source material.

**Comment by mikan66** [comment]
Reopened see discussion at; https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/102#issuecomment-1233583636

**Comment by mikan66** [comment]
Review latest decision at: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/102#issuecomment-1379664479

**Comment by mikan66** [comment]
See updated specs at: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/102#issuecomment-1379664479

**Comment by mikan66** [comment]
Removed embedded debug testing.  Needs real data to test with new FC. 
Commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/5641e942eba28c440672484f866eb0b39ae82ded
