### ISSUE TITLE
Anchorage Area & Shared edges (row 108, 124 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#75]
Sanchez, Alvaro MR: 108
To test Complex line symbology when shared edges exist????

Sanchez, Alvaro MR: 124
KHOA developped new anchorage point symbology (Github # 56) but not sure if this is enough as NIWC requires Curve for testing !?

Also see: 
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/8
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/56

![image](https://user-images.githubusercontent.com/4913543/170318176-f815ff3b-b555-486b-9436-02581cd0d42d.png)

**Comment by DavidGrant-NIWC** [comment]
OBE
