### ISSUE TITLE
Allocate portrayal parameters to SY(CHDATD01) (row 122 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#79]
See https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/13

PortSG-48
![image](https://user-images.githubusercontent.com/4913543/170337718-42de16b8-b236-41cd-b6c8-eeff5f78c36a.png)

**Comment by DavidGrant-NIWC** [comment]
Using viewing group: 31032, viewing group layer: Miscellaneous (Other)
![image](https://user-images.githubusercontent.com/62906211/170791506-a892f039-cd55-4412-aaea-b722f0119df4.png)
