### ISSUE TITLE
Quality of Bathymetric Data (Management of Temporal variation) (row 126 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#80]
![image](https://user-images.githubusercontent.com/4913543/170339651-16939872-49a9-4c35-97f2-6a91b26e9244.png)

https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/4

Should all the QoBD be combined into one issue?  i.e. #66

**Comment by DavidGrant-NIWC** [comment]
Retain test label - dataset 101AA00DS0003.000 doesn't fully support testing QoBD implementation. See https://github.com/iho-ohi/S-101-Test-Datasets/issues/48
