### ISSUE TITLE
Masking of edges by portrayal rules (row 128 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#81]
![image](https://user-images.githubusercontent.com/4913543/170341126-16ad1a91-de71-47bc-9012-0c305a7e30d4.png)

https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/32

**Comment by DavidGrant-NIWC** [comment]
Reopen if and when there is something to implement in the PC
