### ISSUE TITLE
symbolBox incorrect for FOULGD02.svg

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#84]
symbolBox is offset from svgBox - y is positive but should be negative

![image](https://user-images.githubusercontent.com/62906211/170365561-efea7071-b7b8-4c85-ba48-c95ba10cc63e.png)

**Comment by MikusRL** [comment]
Hi @DavidGrant-NIWC, would you like me to update the svg file to fix that, or have you done that already, as you have closed the case? Thanks.

**Comment by MikusRL** [comment]
Thank you, will check and update that. One clarification question - is symbolBox preffered to or must be exactly the same as svgBox? Does that in any way play on portrayal in ECDIS? When exactly those two are used? Thanks.

**Comment by DavidGrant-NIWC** [comment]
svgBox and symbolBox are not part of SVG tiny or S-100, so I guess they could be whatever we want, however the original S-101 symbols provided svgBox, symbolBox, and pivotPoint for most of the symbols (likely to aid in debugging).

In the current S-101 PC, if you edit the CSS files you can display the symbolBox/svgBox/pivotPoint for all symbols (when present) by changing ".layout {display:none}" to ".layout {display:inline}". You can also alter the appearance of each item by editing the style of ".symbolBox", ".svgBox", and ".pivotPoint".

In our testbed, if symbolBox is provided within a particular symbol we use it to restrict the pick report (to the bounding box of the symbol graphics, rather than the bounding box of the symbol).

symbolBox: The outline of the symbol graphics
svgBox: The outline of the symbol
pivotPoint: Always at 0,0

See S-100 Appendix 9-C for more info, particularly 9-C-3-1.1
![image](https://user-images.githubusercontent.com/62906211/171454417-c1324913-068a-416f-97c1-86207375bd9d.png)

Testbed code:
![image](https://user-images.githubusercontent.com/62906211/171455465-8fae768e-fa12-4815-9693-c88cda9abd21.png)

**Comment by MikusRL** [comment]
Thank you @DavidGrant-NIWC again, very comprehensive answer! Most appreciated. I will try to make the most out of it and will come back to you if some point is still unclear, many thanks!

**Comment by MikusRL** [comment]
By the way, the KHOA Symbol Editor does not have that Pivot point line, I always have to add it in myself, and if any other symbol is opened, then it automatically rewrites completely the values and structure of the svg, once saved. That looks I have a systematic error in all symbols I created. I will fix those. Thanks. Do you have any experience with the KHOA's S-100Toolbox'es Symbol Editor?
