### ISSUE TITLE
Ensure S-52 default portrayal is implemented

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#88]
Check all rules for implementation of S-52 default portrayal as specified in the S-52 DAI files. These rules ensure proper symbolization in cases where attributes are missing/encoded as unknown.

In the snippet below the first BCNCAR row is the default portrayal of the feature, whereas the other entries are for specific attribution.
![image](https://user-images.githubusercontent.com/62906211/176504451-96764adb-b6cb-4073-ae2b-06305eafc475.png)

**Comment by mikan66** [comment]
No issue found with basic rules (spot checked).  Some shared CSPs may need further looks once test data is available to catch features that don't share attributes.

Shared CSP example:  "if (contains(feature.signalGeneration, {3,5,6}) then"   
                      fixed by "if (contains(feature['!signalGeneration'], {3,5,6}) then"
