### ISSUE TITLE
Implement symbology for Pilotage District (row 20 main)

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#94]
Per https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/57

**Comment by mikan66** [comment]
PILBOP02 is shared with PilotBoardingPlace and PilotageDistrict and is not replaced with by symbol from https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/57#issuecomment-1230215522

**Comment by mikan66** [comment]
Dump Ground area represented as Pilotage District: 
Viewing characteristics same as Pilot Boarding Area.
![image](https://user-images.githubusercontent.com/4913543/187738982-3d56fc3e-9dda-4188-b554-94af15100073.png)

See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/f8c8af35f068734872549eeeedf5341eacab6d15

**Comment by TomRichardson6** [comment]
Test Dataset 22 Edtn 4 has been updated to include Pilotage District as an area feature

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0022
