### ISSUE TITLE
Physical AIS Aid to Navigation [PSWG #70]

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#97]
Implement per https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/70

Test using 101GB0050242J

**Comment by MikusRL** [comment]
I will create a new version of symbol S-AIS in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/70 as per discussion in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/37

**Comment by mikan66** [comment]
Latest guidance at: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/70#issuecomment-1379615392

**Comment by mikan66** [comment]
Group and priority need to be finalized. 
![image](https://user-images.githubusercontent.com/4913543/219391633-f61a1a5e-48b0-4d1e-9cc0-556ce2e8fe0b.png)

**Comment by mikan66** [comment]
Updated viewing group, completed.  See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/e6bd6bd04f5552a0f58bac772a915cc2479fc140
