### ISSUE TITLE
Implement Pile for curve and surface geometries

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#98]
Curve and surface geometries were not allowed in S-57. Implement these geometries per [Pile](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/53) and [Pile with categoryOfPile=6 - area of piles](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/51)

Use 101GB0050242J.000 to test area of piles.

**Comment by mikan66** [comment]
See https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/51#issuecomment-1190866975 and following update to symbol files.
