### ISSUE TITLE
Implement UpdateInformation

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101_Portrayal-Catalogue#99]
[Portrayal SWG UpdateInformation issue](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/77)

Currently implemented using testPCB (points) / CHGRD dashed outline (curves/surfaces)

Use 101GB00GB302045.000 surface feature 146 for testing

**Comment by MikusRL** [comment]
Dave, Could you please share here the cell you mentioned, or share the link to its original location? Thanks

**Comment by DavidGrant-NIWC** [comment]
> Dave, Could you please share here the cell you mentioned, or share the link to its original location? Thanks

[Admiralty S-101 Trial Cells](https://datahub.admiralty.co.uk/portal/apps/sites/#/marine-data-portal/items/6966cb7ce9454ccf9afbbd3c9a105f9e)

**Comment by mikan66** [comment]
@alvarosanuy confirming this should actually be bumped to PC 1.2.0 or after?  If not, then we need better guidance on what to implement in 1.1.0.

**Comment by alvarosanuy** [comment]
**This task has been moved to PC 1.2.0 or later (as per label in the PsWG Github space).**
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/78

**Comment by DavidGrant-NIWC** [comment]
Initial implementation - doesn't implement "move" properly because we don't have test data which populates the UpdatedInformation association.

**Comment by DavidGrant-NIWC** [comment]
Closing this as implemented, will create separate issue to address "move".
